  <!-- Main content -->
<section class="content">
  <!-- Main row -->
  <div class="row">
    <!-- Left col -->
    <section class=" col-lg-12 connectedSortable">
         <div class="box box-warning">
                <div class="box-header with-border">
                  <h3 class="box-title">Thông Tin Hồ Sơ</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <form role="form" class="form-horizontal">
                    <!-- text input -->
                    <div class="form-group">
                      <label for="inputName" class="col-sm-3 control-label">Tên Khách Hàng</label>
                      <div class="col-sm-9">
                          <a href="#" id="name-custom" data-type="text" data-pk="1" data-url="/post" data-title="Enter username">Nguyễn Văn A</a>
                      </div>
                     </div>
                    <div class="form-group">
                       <label for="inputName" class="col-sm-3 control-label">Sản Phẩm</label>
                          <div class="col-sm-9">
                           <a href="#" id="name-product" data-type="text" data-pk="1" data-url="/post" data-title="Enter username">An Toàn Lao Động</a>
                          </div>
                    </div>
                    <div class="form-group">
                       <label for="inputName" class="col-sm-3 control-label">Trạng Thái</label>
                          <div class="col-sm-9">
                           <a href="#" id="process" data-type="select" data-pk="1" data-url="/post" data-title="Enter username"></a>
                          </div>
                    </div>
                    <div class="row">
                          <section class="col-lg-6 connectedSortable">
                            <div class="box box-primary">
                               <div class="box-header with-border">
                                <h3 class="box-title">Khách Hàng</h3>
                              </div><!-- /.box-header -->
                            
                             <div class="box-body">
                               <div class="row">
                               <div class=" col-lg-6 form-group">
                                  <label for="inputName" class="col-sm-6 control-label">Người Gửi</label>
                                  <div class="col-sm-6">
                                        <a href="#" id="name-agency" data-type="select" data-pk="1" data-url="/post" data-title="Enter username"></a>
                                  </div>
                                </div>
                                <div class="col-lg-6 form-group">
                                  <label for="inputName" class="col-sm-6 control-label">Thỏa Thuận</label>
                                  <div class="col-sm-6">
                                    <a href="#" id="money-custom" data-type="text" data-pk="1" data-url="/post" data-title="Enter username">500,000</a>
                                  </div>
                                </div>
                                 </div>
                                <div class="row">
                                   <div class=" col-lg-6 form-group ">
                                    <label for="inputName" class="col-sm-6 control-label">Ngày Nhận</label>
                                    <div class="col-sm-6">
                                      <a href="#" id="cus-date-start" data-type="combodate" data-pk="1" data-url="/post" data-title="Enter username">15/05/1984</a>
                                    </div>
                                  </div>
                                   <div class=" col-lg-6 form-group">
                                    <label for="inputName" class="col-sm-6 control-label">Ngày Hẹn</label>
                                    <div class="col-sm-6">
                                      <a href="#" id="cus-date-end" data-type="combodate" data-pk="1" data-url="/post" data-title="Enter username">15/05/1984</a>
                                    </div>
                                  </div>
                                    
                                </div>
                               
                            </div>
                        </div>
                        <!-- TAB -->
                        <div class="nav-tabs-custom">
                                <ul class="nav nav-tabs">
                                  <li class="active"><a href="#activity" data-toggle="tab">Thanh Toán</a></li>
                                  <li><a href="#timeline" data-toggle="tab">Bình Luận</a></li>
                                  <li><a href="#settings" data-toggle="tab">Tài Liệu</a></li>
                                </ul>
                                <div class="tab-content">
                                  <div class="active tab-pane" id="activity">
    
                                  </div><!-- /.tab-pane -->
                                  <div class="tab-pane" id="timeline">
                                     <div class="box-body chat" id="chat-box">
                                      <!-- chat item -->
                                      <div class="item">
                                        <img src="dist/img/user4-128x128.jpg" alt="user image" class="online">
                                        <p class="message">
                                          <a href="#" class="name">
                                            <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 2:15</small>
                                            Mike Doe
                                          </a>
                                          I would like to meet you to discuss the latest news about
                                          the arrival of the new theme. They say it is going to be one the
                                          best themes on the market
                                        </p>
                                        <div class="attachment">
                                          <h4>Attachments:</h4>
                                          <p class="filename">
                                            Theme-thumbnail-image.jpg
                                          </p>
                                          <div class="pull-right">
                                            <button class="btn btn-primary btn-sm btn-flat">Open</button>
                                          </div>
                                        </div><!-- /.attachment -->
                                      </div><!-- /.item -->
                                      <!-- chat item -->
                                      <div class="item">
                                        <img src="dist/img/user3-128x128.jpg" alt="user image" class="offline">
                                        <p class="message">
                                          <a href="#" class="name">
                                            <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 5:15</small>
                                            Alexander Pierce
                                          </a>
                                          I would like to meet you to discuss the latest news about
                                          the arrival of the new theme. They say it is going to be one the
                                          best themes on the market
                                        </p>
                                      </div><!-- /.item -->
                                      <!-- chat item -->
                                      <div class="item">
                                        <img src="dist/img/user2-160x160.jpg" alt="user image" class="offline">
                                        <p class="message">
                                          <a href="#" class="name">
                                            <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 5:30</small>
                                            Susan Doe
                                          </a>
                                          I would like to meet you to discuss the latest news about
                                          the arrival of the new theme. They say it is going to be one the
                                          best themes on the market
                                        </p>
                                      </div><!-- /.item -->
                                    </div><!-- /.chat -->
                                    <div class="box-footer">
                                      <div class="input-group">
                                        <input class="form-control" placeholder="Type message...">
                                        <div class="input-group-btn">
                                          <button class="btn btn-success"><i class="fa fa-plus"></i></button>
                                        </div>
                                      </div>
                                    </div>
                                  </div><!-- /.tab-pane -->

                                  <div class="tab-pane" id="settings">
                                  
                                  </div><!-- /.tab-pane -->
                                </div><!-- /.tab-content -->
                              </div><!-- /.nav-tabs-custom -->
                          </section>
                           <section class="col-lg-6 connectedSortable">
                            <div class="box box-info">
                               <div class="box-header with-border">
                                <h3 class="box-title">Nhà Cung Cấp</h3>
                              </div><!-- /.box-header -->
                               <div class="box-body">
                             <div class="form-group">
                                <label for="inputName" class="col-sm-3 control-label">Xử Lý</label>
                                <div class="col-sm-9">
                                  <select class="form-control">
                                    <option>RDC</option>
                                    <option>Nguyễn A</option>
                                    <option>Văn B</option>
                                  </select>
                                </div>
                              </div>
                                  <div class="form-group">
                                  <label for="inputName" class="col-sm-3 control-label">Thỏa Thuận</label>
                                  <div class="col-sm-9">
                                    <input type="text" class="form-control"  >
                                  </div>
                                </div>
                                <div class="form-group">
                                  <label for="inputName" class="col-sm-3 control-label">Ngày Nhận</label>
                                  <div class="col-sm-9">
                                    <input id="pro-date-start"type="text" class="form-control"  >
                                  </div>
                                </div>
                                 <div class="form-group">
                                  <label for="inputName" class="col-sm-3 control-label">Ngày Hẹn</label>
                                  <div class="col-sm-9">
                                    <input id="pro-date-end"type="text" class="form-control"  >
                                  </div>
                                </div>
                               </div>
                             </div>
                          </section>
                    </div>
                  </form>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
    </section><!-- /.Left col -->
    <!-- right col (We are only adding the ID to make the widgets sortable)-->
   
  </div><!-- /.row (main row) -->

</section><!-- /.content -->
<script type="text/javascript">
  $('#name-custom').editable();
  $('#name-product').editable();
  $('#money-custom').editable();
  $('#cus-date-start').editable({
        format: 'yyyy-mm-dd',    
        viewformat: 'dd/mm/yyyy',    
        datepicker: {
                weekStart: 1
           }
        }
    );
   $('#cus-date-end').editable({
        format: 'yyyy-mm-dd',    
        viewformat: 'dd/mm/yyyy',    
        datepicker: {
                weekStart: 1
           }
        }
    );
  $('#process').editable({
        value: 1,    
        source: [
              {value: 1, text: 'Nhận Hồ Sơ'},
              {value: 2, text: 'Đang Sử Lý'},
              {value: 3, text: 'Sử Lý Xong'},
              {value: 4, text: 'Giao Hồ Sơ'},
              {value: 5, text: 'Đóng'},
           ]
    });
  $('#name-agency').editable({
        value: 1,    
        source: [
              {value: 1, text: 'Nguyễn Văn A'},
              {value: 2, text: 'Nguyễn Văn B'},
              {value: 3, text: 'Nguyễn Văn C'},
           ]
    });
  </script>