<section class="content">
	<div class="box box-default">
		  <div class="box-header with-border">
		    <h3 class="box-title">Tìm Kiếm Nâng Cao</h3>
		    <div class="box-tools pull-right">
		      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
		    </div><!-- /.box-tools -->
		  </div><!-- /.box-header -->
		  <div class="box-body" >
		  		<div class="form-horizontal">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="inputEmail3" class="col-sm-1 control-label col-custum">Nhận Từ</label>
                      <div class="col-sm-2 col-custum">
                        <input type="email" class="form-control" id="cus-date-start_1">
                      </div>
                      <label for="inputEmail3" class="col-sm-1 control-label col-custum">Đến</label>
                       <div class="col-sm-2 col-custum">
                       <input type="email" class="form-control" id="cus-date-start_2" >
                      </div>
                        <label for="inputEmail3" class="col-sm-1 control-label">Trả Từ</label>
                      <div class="col-sm-2">
                        <input type="email" class="form-control" id="cus-date-end_1">
                      </div>
                      <label for="inputEmail3" class="col-sm-1 control-label">Đến</label>
                       <div class="col-sm-2">
                       <input type="email" class="form-control" id="cus-date-end_2" >
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">Đại Lý</label>
                      <div class="col-sm-2">
                         <select id="agency_id"class="form-control js-example-basic-single" name="agency_id" >
                               <?php foreach($agencys as $agency){
                                 echo "<option  value=".$agency->getId().">".$agency->getUsername()."</option>";
                                }?>
                          </select>
                      </div>
                      <label for="inputEmail3" class="col-sm-2 control-label">Trạng Thái</label>
                      <div class="col-sm-2">
                         <select id="process_id"class="form-control js-example-basic-single" name="agency_id" >
                          		<option  value="0">Tất Cả</option>;
                               <?php foreach($processes as $process){
                                 echo "<option  value=".$process->id.">".$process->name."</option>";
                                }?>
                          </select>
                      </div>
                      <label for="inputEmail3" class="col-sm-2 control-label">Nhà Cung Cấp</label>
                      <div class="col-sm-2">
                         <select id="provider_id"class="form-control js-example-basic-single" name="agency_id" >
                               <?php foreach($agencys as $agency){
                                 echo "<option  value=".$agency->getId().">".$agency->getUsername()."</option>";
                                }?>
                          </select>
                      </div>
                    </div>
                    <div class="form-group">
	                       
	                        <label class="col-sm-2 control-label">Người Chịu Trách Nhiệm</label>
	                         <div class="col-sm-3">
	                        <select class="form-control js-example-basic-single" id="assign_id" >
	                        <option  value="0">Tất Cả</option>
	                           <?php foreach($staffs as $staff){
	                             echo "<option  value=".$staff->id.">".$staff->username."</option>";
	                            }?>
	                          </select>
	                         </div>
	                          <label class="col-sm-2 control-label">Người Giám Sát</label>
	                         <div class="col-sm-3">
	                        	<select class="form-control js-example-basic-single" id="reporter_id" >
	                        	<option  value="0">Tất Cả</option>
		                           <?php foreach($staffs as $staff){
		                             echo "<option  value=".$staff->id.">".$staff->username."</option>";
		                            }?>
	                          	</select>
	                         </div>
	                         <div class="col-sm-2">
	                         	<button class="btn btn-block btn-primary" onclick="export_pdf()"><span class="glyphicon glyphicon-print"></span></button>

	                         </div>
                    </div>
                    <div>
                  </div><!-- /.box-body -->
            <div class="row">
	            <div class="col-sm-2">
			  		<button class="btn btn-block btn-primary" onclick="pay_action(1)">Đại Lý Thành Toán</span></button>
			  	</div>
			  	<div class="col-sm-2">
			  		<button class="btn btn-block btn-default" onclick="show_detail()">Xem Chi Tiết</span></button>
			  	
			  	</div>
			  	<div class="col-sm-3">
			  		<button class="btn btn-block btn-danger" onclick="pay_action(2)">Thanh Toán Cho Nhà Cung Cấp</button>
			  	</div>
			  	<div class="col-sm-2">
			  		<button class="btn btn-block btn-info" onclick="add_action()"><span class="glyphicon glyphicon-plus"></span>Thêm Hồ Sơ</button>
			  	</div>
		  </div>
    </div>
		  </div><!-- /.box-body -->
		
	</div><!-- /.box -->
	
	<div>
		Ẩn Hiện: 
		<a class="toggle-vis" data-column="1">Tên</a>
		 - <a class="toggle-vis" data-column="2">Hồ Sơ</a>
		 - <a class="toggle-vis" data-column="3">Trạng Thái</a> 
		  - <a class="toggle-vis" data-column="4">Người Gửi</a> 
		 - <a class="toggle-vis" data-column="5">Thỏa Thuận</a> 
		  - <a class="toggle-vis" data-column="6">Đã Nhận</a>
		 - <a class="toggle-vis" data-column="7">Ngày Nhận</a> 
		 - <a class="toggle-vis" data-column="8">Ngày Trả</a> 
		 -<a class="toggle-vis" data-column="9">Xỷ Lý</a>
		 -<a class="toggle-vis" data-column="10">Phải Chi</a>
		-<a class="toggle-vis" data-column="11">Đã Chi</a>
		-<a class="toggle-vis" data-column="12">Ngày Xử Lý</a>
		-<a class="toggle-vis" data-column="13">Xử Lý Xong</a>
		-<a class="toggle-vis" data-column="14">Người Chịu Trách Nhiệm</a>
		-<a class="toggle-vis" data-column="15">Người Giám Sát</a>
	</div>
	<table id="users-table" class="display nowrap" cellspacing="0" width="100%">
	  
	          <thead>
	        
	            <tr>
	            	<th>#</th>
	                <th>Tên</th>
	                <th>Hồ Sơ</th>
	                <th>Trạng Thái</th>
	               	<th>Người Gửi</th>
	               	<th>Thỏa Thuận</th>
	               	<th>Đã Nhận</th>
	               	<th>Ngày Nhận</th>
	               	<th>Ngày Trả</th>
	               	<th>Xỷ Lý</th>
	               	<th>Phải Chi</th>
	               	<th>Đã Chi</th>
	               	<th>Ngày Xử Lý</th>
	               	<th>Xử Lý Xong</th>
	               	<th>Người Chịu Trách Nhiệm</th>
	               	<th>Người Giám Sát</th>
	            </tr>
	        </thead>
	        <tfoot>
	            <tr>
	            	<th>#</th>
	                <th>Tên</th>
	                <th>Hồ Sơ</th>
	                <th>Trạng Thái</th>
	               	<th>Người Gửi</th>
	               	<th>Thỏa Thuận</th>
	               	<th>Đã Nhập</th>
	               	<th>Ngày Nhận</th>
	               	<th>Ngày Trả</th>
	               	<th>Xỷ Lý</th>
	               	<th>Phải Chi</th>
	               	<th>Đã Chi</th>
	               	<th>Ngày Xử Lý</th>
	               	<th>Xử Lý Xong</th>
	               	<th>Người Chịu Trách Nhiệm</th>
	               	<th>Người Giám Sát</th>
	            </tr>
	        </tfoot>
	</table>
</section>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="pay-modal-lable">Thêm Hồ Sơ</h4>
      </div>
      <div class="modal-body">
      		<div class="row">
      			<div class="col-sm-6">
      				<div class="form-group">
                      <label>Tên Khách Hàng</label>
                      <input type="text" class="form-control" name="custumer" placeholder="Tên Khách Hàng">
                    </div>
                    <div class="form-group">
                      <label>Sản Phẩm</label>
                      <input type="text" class="form-control" name="certificate"  >
                    </div>
                    <div class="form-group">
                      <label>Người Giám Sát</label>
                      <input type="text" class="form-control" name="custumer" placeholder="Tên Khách Hàng">
                    </div>
                    <div class="form-group">
                      <label>Người Chịu Trách Nhiệm</label>
                      <input type="text" class="form-control" name="certificate"  >
                    </div>
      			</div>
      			<div class="col-sm-6">
      				<div class="form-group">
                      <label>Đại Lý</label>
                      <input type="text" class="form-control" name="custumer" placeholder="Tên Khách Hàng">
                    </div>
                    <div class="form-group">
                      <label>Thỏa Thuận</label>
                      <input type="text" class="form-control" name="certificate"  >
                    </div>
                    <div class="form-group">
                      <label>Ngày Nhận</label>
                      <input type="text" class="form-control" name="custumer" placeholder="Tên Khách Hàng">
                    </div>
                    <div class="form-group">
                      <label>Ghi Chú</label>
                      <input type="text" class="form-control" name="certificate"  >
                    </div>
      			</div>
      		</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
        <button type="button"  class="btn btn-primary" id="btn_submit">Tạo</button>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript" language="javascript" class="init">
	
var editor; // use a global for the submit and return data rendering in the examples

	/*$('#users-talbe').DataTable( {
		dom: 'lrtip',
		processing: true,
        serverSide: true,
        ajax: {
            url: "/manager-users/getlist",
            type: "POST"
        },
		columns: [
			{ data: "username" },
			{ data: "role" },
			{ data: "staus" }
		],
		order: [[ 3, "desc" ]],
		buttons: [
			{ extend: "create", editor: editor },
			{ extend: "edit",   editor: editor },
			{ extend: "remove", editor: editor }
		]
	} );*/
		var table = $('#users-table').DataTable( {
						"dom": '<"top"iflp<"clear">>rt<"bottom"iflp<"clear">>',
						"processing": true,
				        "serverSide": true,
				        "scrollX": true,
				        ajax: {
				            url: "/manager-tasks/getlist",
				            type: "POST"
				        },
				        "language": {
				    		"url": "//cdn.datatables.net/plug-ins/1.10.10/i18n/Vietnamese.json"
				  		},
				  		"lengthMenu": [ 20, 50,75, 100 ],
						columns: [
							{ data: "DT_RowId" },
							{ data: "custumer" },
							{ data: "certificate" },
							{ data: "process_name" },
							{ data: "agency_name" },
							{ data: "cost_sell" },
							{ data: "custumer_pay" },
							{ data: "date_open" },
							{ data: "date_end" },
							{ data: "provider_name" },
							{ data: "cost_buy" },
							{ data: "provider_pay" },
							{ data: "date_open_pr" },
							{ data: "date_end_pr" },							
							{ data: "assign_name" },
							{ data: "reporter_name" },
						],

				} );
	 $('#users-table').on('click', 'tr', function () {
	 	 $(this).toggleClass('selected');
      //  var data = table.row( this ).id();
        //window.open("/manager-tasks/detail/"+data);
    } );
	 function onpen_new_tab(id){
	 		window.open("/manager-tasks/detail/"+id);
	 }
	 function show_detail(){

	 	 var data = table.rows('.selected').data();
	 	 if(data.length == 0){
	 	 	 alert( "Chưa có hồ sơ nào được chọn");
	 	 	 return;
	 	 }
	 	 for(var i = 0; i<data.length;i++){
	 	 	var id = data[i]['DT_RowId'];
	 	 	setTimeout(onpen_new_tab, i*1000,id);
	 	 }

	 }
	 function pay_action(type){
	 	var data = table.rows('.selected').data();
	 	 if(data.length == 0){
	 	 	 alert( "Chưa có hồ sơ nào được chọn");
	 	 	 return;
	 	 }
	 	 var user_id = 0;
	 	 if(type == 1 && $("#agency_id").val() == 0 ){
	 	 	alert( "Chưa Chọn Đại Lý");
	 	 	 return;
	 	 }
	 	 if(type == 2 && $("#provider_id").val() == 0 ){
	 	 	alert( "Chưa Chọn Nhà Cung  Cấp");
	 	 	 return;
	 	 }
	 	 
	 	 var id = ""
	 	 for(var i = 0; i<data.length;i++){
	 	 	id += data[i]['DT_RowId']+',';
	 	 }
	 	 if(type == 1){
	 	 	user_id = $("#agency_id").val();
	 	 }else{
	 	 	user_id = $("#provider_id").val();
	 	 }
	 	 window.open("/pay/pay?user_id="+user_id+"&type="+type+"&id="+id);
	 }
	 $('a.toggle-vis').on( 'click', function (e) {
        e.preventDefault();
 
        // Get the column API object
        var column = table.column( $(this).attr('data-column') );
        if($(this).hasClass('toggle-vis-hide')){
        	$(this).removeClass('toggle-vis-hide');
        }else{
			$(this).addClass('toggle-vis-hide');
        }
 		
        // Toggle the visibility
        column.visible( ! column.visible() );
    } );


     $("#agency_id").select2().on("change", function(e) {
          // mostly used event, fired to the original element when the value changes
           	$('#users-table').DataTable().column(4).search( e.val,"","").draw();
      });
     $("#provider_id").select2().on("change", function(e) {
          // mostly used event, fired to the original element when the value changes
           	$('#users-table').DataTable().column(9).search( e.val,"","").draw();
      });
       $("#process_id").select2().on("change", function(e) {
          // mostly used event, fired to the original element when the value changes
           	$('#users-table').DataTable().column(3).search( e.val,"","").draw();
      });
        $("#assign_id").select2().on("change", function(e) {
          // mostly used event, fired to the original element when the value changes
           	$('#users-table').DataTable().column(14).search( e.val,"","").draw();
      });
         $("#reporter_id").select2().on("change", function(e) {
          // mostly used event, fired to the original element when the value changes
           	$('#users-table').DataTable().column(15).search( e.val,"","").draw();
      });
      function seach_custum_date_start(){
      		$('#users-table').DataTable().column(7).search( $("#cus-date-start_1").val()+"-"+$("#cus-date-start_2").val(),"","").draw();
      }
      function seach_custum_date_end(){
      		$('#users-table').DataTable().column(8).search( $("#cus-date-end_1").val()+"-"+$("#cus-date-end_2").val(),"","").draw();
      }
    $("#cus-date-start_1").datepicker({
	  onSelect: function(dateText) {
	     seach_custum_date_start();
	  }
	});

    
    $("#cus-date-start_1").datepicker( "option", "dateFormat", "dd/mm/yy");
     $("#cus-date-start_2").datepicker({
	  onSelect: function(dateText) {
	      seach_custum_date_start();
	  }
	});
    $("#cus-date-start_2").datepicker( "option", "dateFormat", "dd/mm/yy");
      $("#cus-date-end_1").datepicker({
	  onSelect: function(dateText) {
	     seach_custum_date_end();
	  }
	});
    $("#cus-date-end_1").datepicker( "option", "dateFormat", "dd/mm/yy");
    $("#cus-date-end_2").datepicker({
	  onSelect: function(dateText) {
	      seach_custum_date_end();
	  }
	});
	function add_action(){
    	

    	$("#myModal").modal('show');
    
  }
    $("#cus-date-end_2").datepicker( "option", "dateFormat", "dd/mm/yy");
     function export_pdf(){
     	window.location ='/manager-tasks/export-pdf'
   /*   var data = table.ajax.params(); 
      for(var i = 0; i<data.columns.length ;i++){
      	data.columns[i].visible = table.column( i ).visible();
      }
        $.ajax({
            type:"POST",                          
            url:"/manager-tasks/export-pdf",
            data:data,
            success: function(data){
                     

            }
     	});*/
      	
     }
   
</script>