<?php
		/* @var $escaper \Zend\View\Helper\EscapeHtmlAttr */
		$escaper = $this->view->plugin('escapeHtmlAttr');
		/* @var $navigation \Zend\View\Helper\Navigation */
		$navigation = $this->view->navigation(); // ; // ->view->plugin('navigation'); // ->view->navigation(); //
		/* @var $maxlevel number */
		$maxlevel = $this->menu->getMaxDepth();
		/* @var $isBelowMaxLevel boolean */
		$isBelowMaxLevel = ($maxlevel > $level) || ($maxlevel === null) || ($maxlevel === false);
	
		if (null === $container) {
			$container = $this->menu->getContainer()->pages;
		}
	
		/* @var $html string the menu html string */
		$html = '<ul class="' . ($level == 0 ? $this->menu->getUlClass() : ($level == 1 ? $this->menu->getSubUlClassLevel1() : $this->menu->getSubUlClass())) . ' level_' . $level . '">' . PHP_EOL;
		//foreach ($container as $page):
		foreach ($container as $page):
		if ($navigation->accept($page)):
		echo '<!-- '.$page->getLabel().' --> ';
		$classnames = array();
	
		if (!empty($this->menu->getDefaultLiClass())) {
			$classnames[] = $this->menu->getDefaultLiClass();
		}
		if (!empty($page->pages) && $isBelowMaxLevel) {
			$classnames[] = ($level == 0 ? $this->menu->getSubLiClassLevel0() : $this->menu->getSubLiClass());
		}
		if ($page->isActive(true)) {
			$classnames[] = $this->menu->getLiActiveClass();
		}
	
		$html .= '<li class="'.(implode(" ", $classnames)).'">' . PHP_EOL;
		if (!empty($page->pages) && $isBelowMaxLevel) {
			$href = (
					!empty($this->menu->getHrefSubToggleOverride()) ?
					$this->menu->getHrefSubToggleOverride() : $page->getHref()
					);
			$html .= '<a class="dropdown-toggle" data-toggle="' . ($level == 0 ? $this->menu->getSubLiClassLevel0() : $this->menu->getSubLiClass()) . '" href="' . $href . '">' . PHP_EOL .
			($page->get('icon') ? '<span class="' . $this->menu->getIconPrefixClass() . '' . $page->get('icon') . '"></span> ' : '' ) . PHP_EOL .
			$page->getLabel() .
			'</a>' . PHP_EOL;
		} else {
			$html .= '<a href="' . $page->getHref() . '">' . PHP_EOL .
			($page->get('icon') ? '<span class="' . $this->menu->getIconPrefixClass() . '' . $page->get('icon') . '"></span> ' : '' ) . PHP_EOL .
			$page->getLabel().
			'</a>' . PHP_EOL;
		}
		if (!empty($page->pages)):
		// ... ;
		if ( $isBelowMaxLevel ) {
			//$html .= $this->render( $page->pages, $level+1 );
			foreach ($page->pages as $key => $subpage) {
				$html .= $this->menu->renderPartial( $subpage, null, $level+1 );
				//$html .= $this->menu->renderPartial( $subpage, $this->menu->getPartial(), $level+1 );
			}
			
		}
		endif;
	
		$html .= '</li>' . PHP_EOL;
		endif;
		endforeach;
		$html .= '</ul>' . PHP_EOL;
	
		echo $html;
?>