<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TwitterBootstrapAPI\Module'                        => __DIR__ . '/Module.php',
    'TwitterBootstrapAPI\Framework\TestCase'        => __DIR__ . '/tests/TwitterBootstrapAPI/Framework/TestCase.php',
);
