              <!-- TO DO List -->
              <div class="box box-primary">
                <div class="box-header">
                  <i class="ion ion-clipboard"></i>
                  <h3 class="box-title">Log List</h3>
                  <div class="box-tools pull-right">
                    <ul class="pagination pagination-sm inline">
                      <li><a href="#">&laquo;</a></li>
                      <li><a href="#">1</a></li>
                      <li><a href="#">2</a></li>
                      <li><a href="#">3</a></li>
                      <li><a href="#">&raquo;</a></li>
                    </ul>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <ul class="todo-list">
                  <?php
                    foreach ($logs as $log) {
                      $task = json_decode( $log->value, false );?>
                      <li>
                      <!-- drag handle -->
                      <!-- checkbox -->
                      <!-- todo text -->
                        <span class="text"> <?php echo $task->custumer." ". $log->action_id. " vào ngày " .$task->date_open;?> </span>
                           <small class="label label-info"><i class="fa fa-clock-o"></i> Show detail</small>
                           <!-- General tools such as edit or delete-->
                           <div class="tools">
                             <i class="fa fa-edit"></i>
                             <i class="fa fa-trash-o"></i>
                           </div>
                        </li>
                  <?php
                      }
                  ?>
                  </ul>
                </div><!-- /.box-body -->
              </div><!-- /.box -->