              <!-- TO DO List -->
              <div class="box box-primary">
                <div class="box-header">
                  <i class="ion ion-clipboard"></i>
                  <h3 class="box-title">Log List</h3>
                  <div class="box-tools pull-right">
                    <ul class="pagination pagination-sm inline">
                      <li><a href="#">&laquo;</a></li>
                      <li><a href="#">1</a></li>
                      <li><a href="#">2</a></li>
                      <li><a href="#">3</a></li>
                      <li><a href="#">&raquo;</a></li>
                    </ul>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <ul class="todo-list">
                      <li>
                      <!-- drag handle -->
                      <!-- checkbox -->
                      <!-- todo text -->
                        <span class="text"> <?php
                        if ( !empty($data) ) {
                            $task = json_decode( $data['value'], true );
                            echo "User: đã thay đổi: " . $task['key']. " từ: ".$task['old_value'] . " thành: " .$task['new_value'];
                        }
                        ?> </span>
                           <!-- General tools such as edit or delete-->
                           <div class="tools">
                             <i class="fa fa-edit"></i>
                             <i class="fa fa-trash-o"></i>
                           </div>
                        </li>
                  </ul>
                </div><!-- /.box-body -->
              </div><!-- /.box -->