<?php
use Application\Config\Config;
use Utility\Date\Date;
?>
<!-- TO DO List -->
<div class="box box-primary">
<div class="box-header">
  <i class="ion ion-clipboard"></i>
  <h3 class="box-title">Lịch Sử Thay Đổi</h3>
  <div class="box-tools pull-right">
  <?php
 // add at the end of the file after the table
 echo $this->paginationControl(
     // the paginator object
     $this->logs,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     'partial/paginator.phtml',
     // the route to link to when a user clicks a control link
     array(
         'route' => 'log/showlog',
         'data_route'=>array(
            'id'=> $task_id
         )
     )
 );
 ?>

  </div>
</div><!-- /.box-header -->
<div class="box-body">
  <ul class="todo-list">
  <?php foreach ($logs as $log) {
      /* Decode to array */
      $task = json_decode($log->value, true);
   ?>
      <li>
      <!-- drag handle -->
      <!-- checkbox -->
      <!-- todo text -->
        <span class="text">
            <!-- user link -->
            <a class="foucus-value" href="/profile/user-info/<?php echo $log->user_id; ?>"><?php echo $log->join_user_name; ?></a>

            <!-- Action edit -->
            <?php if ($log->action_id == (string)Config::EDIT_ACTION) {
                echo " đã thay đổi " . "<span class='foucus-value'>".$task['key_name']."</span>"; ?>
                <?php if (! empty($task['custumer'])) echo "của khách hàng <span class='foucus-value'>" . $task['custumer']. "</span>, chứng chỉ "; else echo " của chứng chỉ: "; ?>

                <a class ="foucus-value" href="/manager-tasks/detail/<?php echo $log->task_id; ?>"> <?php echo $log->join_task_name; ?> </a>
                <!-- If field reporter_id, agency_id ... -->
                <?php echo " từ "; ?>
                <?php if ($task['key'] == Config::reporter_id
                        || $task['key'] == Config::provider_id
                        || $task['key'] == Config::agency_id
                        || $task['key'] == Config::assign_id) {?>
                    <!-- Org link -->
                    <a class ="old-value foucus-value"href="/profile/user-info/<?php echo $task['old_id']; ?>"> <?php echo $task['old_value']; ?> </a>
                    <?php echo " sang "; ?>
                    <!-- new link -->
                    <a class ="foucus-value" href="/profile/user-info/<?php echo $task['new_id']; ?>"> <?php echo $task['new_value']; ?> </a> <?php
                } else if ($task['key'] == Config::process_id) {
                    echo "<span class='old-value foucus-value'>".$task['old_value'] ."</span>". " sang " ."<span class='new-value foucus-value'>".$task['new_value']."</span>";
                }  else if ($task['key'] == Config::date_open_id
                        || $task['key'] == Config::date_end_id
                        || $task['key'] == Config::date_open_pr_id
                        || $task['key'] == Config::date_end_pr_id) {
                    echo "<span class='old-value foucus-value'>". Date::changeDateSQLtoVN($task['old_id']) ."</span>". " sang " ."<span class='new-value foucus-value'>". Date::changeDateSQLtoVN($task['new_id']) ."</span>";
                } else if ($task['key'] == Config::agency_note_id
                        || $task['key'] == Config::provider_note_id) { ?>
                    <a href="#" data-toggle="tooltip" title="<?php echo $task['old_id']?>"> <?php echo "<span class='old-value foucus-value'>". substr($task['old_id'], 0, 50) ."</span>" ?></a>
                    <?php echo " sang "; ?>
                    <a href="#" data-toggle="tooltip" title="<?php echo $task['new_id']?>"> <?php echo "<span class='new-value foucus-value'>". substr($task['new_id'], 0, 50) ."</span>"; ?></a>
                <?php } else {
                    echo "<span class='old-value foucus-value'>".$task['old_id'] ."</span>". " sang " ."<span class='new-value foucus-value'>".$task['new_id']."</span>";
                }
            } ?>

            <!-- Action new -->
            <?php if ($log->action_id == (string)Config::ADD_ACTION) {
                echo " đã thêm hồ sơ "?>
                <?php if (! empty($task['custumer'])) echo "của khách hàng <span class='foucus-value'>" . $task['custumer']. "</span>, chứng chỉ "; else echo " của chứng chỉ: "; ?>
                <a href="/manager-tasks/detail/<?php echo $log->task_id; ?>"> <?php echo $log->join_task_name; ?> </a>
                <?php
            }?>
             <?php if ($log->action_id == (string)Config::DELETE_PAY_ACTION) {
                echo " đã xóa <span class='foucus-value'> Thanh Toán</span> ";
                if ($task['type'] == 1) echo " (Bên Khách Hàng) ";
                else echo "(Bên Nhà Cung Cấp) ";
                echo "<span class='old-value foucus-value'>".number_format($task['money'])."</span>";
                echo "cho hồ sơ "?>
                <?php if (! empty($task['custumer']))
                    echo "của <span class='foucus-value'>" . $task['custumer']. "</span>, chứng chỉ ";
                else echo " của chứng chỉ: "; ?>
                <a href="/manager-tasks/detail/<?php echo $log->task_id; ?>"> <?php echo $log->join_task_name; ?> </a>
                <?php
            }?>
             <!-- Action pay -->
            <?php if ($log->action_id == (string)Config::COMMENT_ACTION) {
                echo " đã <span class='foucus-value'> Thêm bình luận</span> ";
                echo "<span class='new-value  foucus-value'>".substr($task['comment'],0,10)."...</span>";
                echo "cho hồ sơ "?>
                <?php if (! empty($task['custumer']))
                    echo "của <span class='foucus-value'>" . $task['custumer']. "</span>, chứng chỉ ";
                else echo " của chứng chỉ: "; ?>
                <a href="/manager-tasks/detail/<?php echo $log->task_id; ?>"> <?php echo $log->join_task_name; ?> </a>
                <?php
            }?>
             <?php if ($log->action_id == (string)Config::FILE_ACTION) {
                echo " đã <span class='foucus-value'> Thêm tài liệu</span> ";
                echo "<span class='new-value  foucus-value'>".$task['file_name']."</span>";
                echo "cho hồ sơ "?>
                <?php if (! empty($task['custumer']))
                    echo "của <span class='foucus-value'>" . $task['custumer']. "</span>, chứng chỉ ";
                else echo " của chứng chỉ: "; ?>
                <a href="/manager-tasks/detail/<?php echo $log->task_id; ?>"> <?php echo $log->join_task_name; ?> </a>
                <?php
            }?>
            <?php if ($log->action_id == (string)Config::DELETE_FILE_ACTION) {
                echo " đã <span class='foucus-value'> Xóa tài liệu</span> ";
                echo "<span class='old-value  foucus-value'>".$task['file_name']."</span>";
                echo "cho hồ sơ "?>
                <?php if (! empty($task['custumer']))
                    echo "của <span class='foucus-value'>" . $task['custumer']. "</span>, chứng chỉ ";
                else echo " của chứng chỉ: "; ?>
                <a href="/manager-tasks/detail/<?php echo $log->task_id; ?>"> <?php echo $log->join_task_name; ?> </a>
                <?php
            }?>
            <!-- Action pay -->
            <?php if ($log->action_id == (string)Config::PAY_ACTION) {
                echo " đã <span class='foucus-value'> Thanh Toán</span> ";
                if ($task['type'] == 1) echo " (Bên Khách Hàng) ";
                else echo "(Bên Nhà Cung Cấp) ";
                echo "<span class='foucus-value'>".number_format($task['money'])."</span>";
                echo "cho hồ sơ "?>
                <?php if (! empty($task['custumer']))
                    echo "của <span class='foucus-value'>" . $task['custumer']. "</span>, chứng chỉ ";
                else echo " của chứng chỉ: "; ?>
                <a href="/manager-tasks/detail/<?php echo $log->task_id; ?>"> <?php echo $log->join_task_name; ?> </a>
                <?php
            }?>
            <?php if ($log->action_id == (string)Config::EDIT_PAY_ACTION) {
                echo " đã <span class='foucus-value'> Chỉnh sửa Thanh Toán</span> ";
                if ($task['new_value']['type'] == 1) echo " (Bên Khách Hàng) ";
                else echo "(Bên Nhà Cung Cấp) ";
                if(trim($task['old_value']['money']) != trim($task['new_value']['money'])){
                  echo "<span class='old-value foucus-value'>".number_format($task['old_value']['money'])."</span>";
                  echo "<span class='new-value foucus-value'>".number_format($task['new_value']['money'])."</span>";
                }
                if(Date::changeDateSQLtoVN($task['old_value']['date_pay']) != Date::changeDateSQLtoVN($task['new_value']['date_pay'])){
                  echo "<span class='old-value foucus-value'>".Date::changeDateSQLtoVN($task['old_value']['date_pay'])."</span>";
                  echo "<span class='new-value foucus-value'>".Date::changeDateSQLtoVN($task['new_value']['date_pay'])."</span>";
                }
                if(trim($task['old_value']['money_option']) != trim($task['new_value']['money_option'])){
                  echo "<span class='old-value foucus-value'>".($task['old_value']['money_option'] == '1'? "Tiền Mặt":"Chuyển Khoản")."</span>";
                  echo "<span class='new-value foucus-value'>".($task['new_value']['money_option'] == '1'? "Tiền Mặt":"Chuyển Khoản")."</span>";
                }
                echo "cho hồ sơ "?>
                <?php if (! empty($task['new_value']['custumer']))
                    echo "của <span class=' foucus-value'>" . $task['new_value']['custumer']. "</span>, chứng chỉ ";
                else echo " của chứng chỉ: "; ?>
                <a href="/manager-tasks/detail/<?php echo $log->task_id; ?>"> <?php echo $log->join_task_name; ?> </a>
                <?php
            }?>
            
            <!-- date -->
            <i><?php echo " vào ngày " ."<i class='foucus-value'>".Date::changeDateSQLtoVN($log->date);?></i></i>
        </span>
        <!-- General tools such as edit or delete-->
      
      </li>
  <?php
      }
  ?>
  </ul>
</div><!-- /.box-body -->
</div><!-- /.box -->