<section class="content">
	<div class="box box-default">
		  <div class="box-header with-border">
		    <h3 class="box-title">Tổng Kết Công Nợ</h3>
		    <div class="box-tools pull-right">
		      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
		    </div><!-- /.box-tools -->
		  </div><!-- /.box-header -->
		  <div class="box-body" >
		  		<table id="users-table" class="display nowrap" cellspacing="0" width="100%">
	  
		          <thead>
		        
		            <tr>
		                <th>Mã TK</th>
		                <th>Đại Lý</th>
		                <th>Hóa Đơn Đại Lý</th>
		               	<th>Đã Nhận</th>
		               	<th>Hóa Đơn NCC</th>
		               	<th>Đã Chi</th>
		               	<th>Nợ</th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		            	<th>Mã TK</th>
		                <th>Đại Lý</th>
		                <th>Hóa Đơn Đại Lý</th>
		               	<th>Đã Nhận</th>
		               	<th>Hóa Đơn NCC</th>
		               	<th>Đã Chi</th>
		               	<th>Nợ</th>
		            </tr>
		        </tfoot>
			</table>	
		  </div><!-- /.box-body -->
		
	</div><!-- /.box -->
	
</section>
<script type="text/javascript" language="javascript" class="init">
	
var editor; // use a global for the submit and return data rendering in the examples

var table = $('#users-table').DataTable( {
			"dom": '<"top"iflp<"clear">>rt<"bottom"iflp<"clear">>',
			"processing": true,
	        "serverSide": true,
	        "scrollX": true,
	        ajax: {
	            url: "/pay/list-debt",
	            type: "POST"
	        },
	        "language": {
	    		"url": "//cdn.datatables.net/plug-ins/1.10.10/i18n/Vietnamese.json"
	  		},
			columns: [
				{ data: "DT_RowId" },
				{ data: "username" },
				{ data: "agency" },
				{ data: "agency_pay" },
				{ data: "provider" },
				{ data: "provider_pay" },
				{ data: "total" },
			],

	} );
	 $('#users-table').on('click', 'tr', function () {
	 	
      var data = table.row( this ).id();
      	$(this).addClass('selected');
      
    } );
	
    
    $("#cus-date-start_1").datepicker( "option", "dateFormat", "dd/mm/yy");
     $("#cus-date-start_2").datepicker({
	  onSelect: function(dateText) {
	      seach_custum_date_start();
	  }
	});
   
   
</script>