<?php
use Application\Config\Config;
use Utility\Date\Date;
use Application\Utility\URLUtilily; 
?>
<section id ="content"class="content">
	<div class="box box-default">
		  <div class="box-header with-border">
		    <h3 class="box-title">
		    	<?php 
		    		if($pay->type == Config::PAY_CUSTUMER){
		    			echo "Hóa Đơn Thanh Toán Của Đại Lý";
		    		}else{
		    			echo "Hóa Đơn Thanh Toán Cho Nhà Cung Cấp";
		    		}
		    	?>
		    	 <span class="label label-default"><?php echo $pay->id;?>
		    </h3>
		    <div class="box-tools pull-right">
		     <!--  <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button> -->
		    </div><!-- /.box-tools -->
		  </div><!-- /.box-header -->
		  <div class="box-body" >
		  	<div class="form-horizontal">
		  	 <label for="inputName" class="col-xs-2 control-label">
		  	 	<?php 
		    		if($pay->type == Config::PAY_CUSTUMER){
		    			echo "Đại Lý";
		    		}else{
		    			echo "Nhà Cung Cấp";
		    		}
		    	?>
		  	 </label>
		  	<label for="inputName" style="text-align: left;color:red
" class="col-xs-2 control-label"> <span><?php echo $pay->username;?></span></label>
		  	</div>
		  	<div class="form-horizontal">
		  	 <label for="inputName" class="col-xs-2 control-label">Ngày Thanh Toán</label>
                  <div class="col-xs-2">
                    <label for="inputName" class=" control-label"><?php echo Date::changeDateSQLtoVN($pay->date_pay);?></label>
                  </div>
		  	</div>
		  	<div class="form-horizontal">
		  	 <label for="inputName" class="col-xs-2 control-label">Phương Thức</label>
              	<div class="col-xs-2">
                    <label for="inputName" class="control-label"><?php echo $pay->pay_name;?></label>
                </div>
		  	</div>
		  </div>
		  <div class="table-responsive"> 
		  		<table class="table table-bordered">
			  		<thead>
			  			<tr> 
			  			<th>#</th>
			  			<th>Mã HS</th>
			  			<th>Tên</th>
			  			<th>Hồ Sơ</th>
			  			<th>Thỏa Thuận</th>
			  			<th>
			  				<?php 
					    		if($pay->type == Config::PAY_CUSTUMER){
					    			echo "Đã Nhận";
					    		}else{
					    			echo "Đã Thanh Toán";
					    		}
					    	?>
			  			</th>
			  			<th>Dư Nợ</th>
			  			<th>Thanh Toán</th> 
			  			</tr> 
			  		</thead>
		  		<tbody>
		  			<?php 
		  			  $index = 1;
		  			  $total = 0;
		  			for ($i = 0;$i < count($datas);$i++) {
		  				$task = $datas[$i];
		  				$total += $task->current_pay;
		  				?>

			  			<tr>
			  			  
				  				<th scope="row"><?php echo $index?></th>
				  				<td><?php echo $task->DT_RowId ?></td>
				  				<td><a href="/manager-tasks/detail/<?php echo $task->DT_RowId ?>"><?php echo $task->custumer ?></a></td>
				  				<td><?php echo $task->certificate ?></td>
				  				<td>
				  					<?php if($pay->type == Config::PAY_CUSTUMER){
						    				echo number_format($task->cost_sell);
						    			}else{
						    				echo number_format($task->cost_buy);
						    			}
						    		 ?>
				  				</td>
				  				<td>
				  					<?php if($pay->type == Config::PAY_CUSTUMER){
					    				echo number_format($task->custumer_pay);
					    			}else{
					    				echo number_format($task->provider_pay);
					    			}
					    		 	?>
				  				</td>
				  				<td>
				  					<?php
				  						$tmp = 0;
				  					 if($pay->type == Config::PAY_CUSTUMER){
					    				$tmp =$task->cost_sell - $task->custumer_pay; 
					    			}else{
					    				$tmp = $task->cost_buy - $task->provider_pay; 
					    			}
					    			echo number_format($tmp);
					    		 	?>
				  				</td>
				  				<td><?php echo number_format($task->current_pay); ?>	
				  				</td>
				  			
			  			</tr>
			  			
		  			<?php $index++;}?>
		  			<input type="hidden" value="<?php echo $index-1 ;?>"name="count">
		  			<input type="hidden" value="<?php echo $user->id ;?>"name="user_id">
		  				<input type="hidden" value="<?php echo $type ;?>"name="type">
		  			<tr>
		  				<th scope="row"></th>
		  				<td></td>
		  	
		  				<td></td>
		  				<td></td>
		  				<td></td>
		  				<td></td>
		  				<td> Tổng </button></td>
		  				<td id="total_pay"><?php echo number_format($total); ?></td>
		  			</tr>
		  		</tbody>
		  	</table>

		  </div> 
		  <div class="row">
		   <div class="col-xs-2 col-xs-offset-8 connectedSortable">
		  	<button class="btn btn-block btn-primary price_match_no_print" onclick="print_bill()"><span class="glyphicon glyphicon-print"> In</span></button>
		  </div>
		   <div class="col-xs-1 connectedSortable">
		   	 <button class="btn btn-block btn-danger price_match_no_print" onclick="show_alert(<?php echo $pay->id;?>)"><span class="glyphicon glyphicon-trash"></span> Xóa</button>
		   </div>
		  		 
		  </div>
		</div>
	</div>

</section><!-- /.content -->
<!-- Modal -->
<div class="modal fade" id="modal-confirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Cảnh Báo</h4>
      </div>
      <div class="modal-body">
            Dữ Liệu sẽ bị xóa!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
        <button type="button" class="btn btn-danger" id="delete-pay" >Xóa</button>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
	function print_bill(){	
		$('#content').printThis();
	}
	function show_alert(id){
 		$("#delete-pay").attr('onclick','delete_pay_action('+id+')');
     	$("#modal-confirm").modal('show');
     }
     function delete_pay_action(id){
     	$.ajax({
            type:"POST",                          
            url:"/pay/delete",
            data:{
                   id:id
                   },
            success: function(data){
            	window.location.href ="/pay";
            }
     });
     }
</script>