<section class="content">
	<div class="box box-default">
		  <div class="box-header with-border">
		    <h3 class="box-title">Tìm Kiếm Nâng Cao</h3>
		    <div class="box-tools pull-right">
		      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
		    </div><!-- /.box-tools -->
		  </div><!-- /.box-header -->
		  <div class="box-body" >
		  		<div class="form-horizontal">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label col-custum">Thanh Toán Từ</label>
                      <div class="col-sm-2 col-custum">
                        <input type="email" class="form-control" id="cus-date-start_1">
                      </div>
                      <label for="inputEmail3" class="col-sm-1 control-label col-custum">Đến</label>
                       <div class="col-sm-2 col-custum">
                       <input type="email" class="form-control" id="cus-date-start_2" >
                      
                    	</div>
                    </div>
                    <div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label"> Tài Khoản</label>
                      <div class="col-sm-2">
                         <select id="username"class="form-control js-example-basic-single" name="agency_id" >
                               <?php foreach($agencys as $agency){
                                 echo "<option  value=".$agency->getId().">".$agency->getUsername()."</option>";
                                }?>
                          </select>
                      </div>
                      <label for="inputEmail3" class="col-sm-2 control-label">Loại</label>
                      <div class="col-sm-2">
                         <select id="type"class="form-control js-example-basic-single" name="agency_id" >
                          		<option  value="0">Tất Cả</option>;
                               	<option  value="1">Thu</option>;
                               	<option  value="2">Chi</option>;
                          </select>
                      </div>
                      
                    </div>
                    <div>
                  </div><!-- /.box-body -->

    			</div>
		  </div><!-- /.box-body -->
		
	</div><!-- /.box -->
	
	<div>
	
	</div>
	<table id="users-table" class="display nowrap" cellspacing="0" width="100%">
	  
	          <thead>
	        
	            <tr>
	            	<th>#</th>
	            	<th>Tiêu Đề</th>
	                <th>Tài Khoản</th>
	                <th>Loại</th>
	                <th>Giá Trị</th>
	               	<th>Ngày Thanh Toán</th>
	               	<th>Người Tạo</th>
	            </tr>
	        </thead>
	        <tfoot>
	            <tr>
	            	<th>#</th>
	            	<th>Tiêu Đề</th>
	                <th>Tài Khoản</th>
	                <th>Loại</th>
	                <th>Giá Trị</th>
	               	<th>Ngày Thanh Toán</th>
	               	<th>Người Tạo</th>
	            </tr>
	        </tfoot>
	</table>
</section>
<script type="text/javascript" language="javascript" class="init">
	
var editor; // use a global for the submit and return data rendering in the examples

	/*$('#users-talbe').DataTable( {
		dom: 'lrtip',
		processing: true,
        serverSide: true,
        ajax: {
            url: "/manager-users/getlist",
            type: "POST"
        },
		columns: [
			{ data: "username" },
			{ data: "role" },
			{ data: "staus" }
		],
		order: [[ 3, "desc" ]],
		buttons: [
			{ extend: "create", editor: editor },
			{ extend: "edit",   editor: editor },
			{ extend: "remove", editor: editor }
		]
	} );*/
		var table = $('#users-table').DataTable( {
						"dom": '<"top"iflp<"clear">>rt<"bottom"iflp<"clear">>',
						"processing": true,
				        "serverSide": true,
				        "scrollX": true,
				        ajax: {
				            url: "/pay/list",
				            type: "POST"
				        },
				        "language": {
				    		"url": "//cdn.datatables.net/plug-ins/1.10.10/i18n/Vietnamese.json"
				  		},
						columns: [
							{ data: "DT_RowId" },
							{ data: "title" },
							{ data: "username" },
							{ data: "type" },
							{ data: "money" },
							{ data: "date_pay" },
							{ data: "user_create" },
							
						],

				} );
	 $('#users-table').on('click', 'tr', function () {
	 	
      var data = table.row( this ).id();
      	$(this).addClass('selected');
        window.open("/pay/detail/"+data);
    } );
	


     $("#username").select2().on("change", function(e) {
          // mostly used event, fired to the original element when the value changes
           	$('#users-table').DataTable().column(1).search( e.val,"","").draw();
      });
     $("#type").select2().on("change", function(e) {
          // mostly used event, fired to the original element when the value changes
           	$('#users-table').DataTable().column(2).search( e.val,"","").draw();
      });
      function seach_custum_date_start(){
      		$('#users-table').DataTable().column(4).search( $("#cus-date-start_1").val()+"-"+$("#cus-date-start_2").val(),"","").draw();
      }
      function seach_custum_date_end(){
      		$('#users-table').DataTable().column(4).search( $("#cus-date-end_1").val()+"-"+$("#cus-date-end_2").val(),"","").draw();
      }
    $("#cus-date-start_1").datepicker({
	  onSelect: function(dateText) {
	     seach_custum_date_start();
	  }
	});

    
    $("#cus-date-start_1").datepicker( "option", "dateFormat", "dd/mm/yy");
     $("#cus-date-start_2").datepicker({
	  onSelect: function(dateText) {
	      seach_custum_date_start();
	  }
	});
   
   
</script>