<section class="content">
	
	<form class="form-horizontal">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="inputEmail3" class="col-sm-1 control-label col-custum">Nhận Từ</label>
                      <div class="col-sm-2 col-custum">
                        <input type="email" class="form-control" id="cus-date-start_1">
                      </div>
                      <label for="inputEmail3" class="col-sm-1 control-label col-custum">Đến</label>
                       <div class="col-sm-2 col-custum">
                       <input type="email" class="form-control" id="cus-date-start_2" >
                      </div>
                        <label for="inputEmail3" class="col-sm-1 control-label">Trả Từ</label>
                      <div class="col-sm-2">
                        <input type="email" class="form-control" id="cus-date-end_1">
                      </div>
                      <label for="inputEmail3" class="col-sm-1 control-label">Đến</label>
                       <div class="col-sm-2">
                       <input type="email" class="form-control" id="cus-date-end_2" >
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">Người Gửi</label>
                      <div class="col-sm-2">
                         <select id="agency_id"class="form-control js-example-basic-single" name="agency_id" >
                               <?php foreach($agencys as $agency){
                                 echo "<option  value=".$agency->getId().">".$agency->getUsername()."</option>";
                                }?>
                          </select>
                      </div>
                      <label for="inputEmail3" class="col-sm-2 control-label">Trạng Thái</label>
                      <div class="col-sm-2">
                         <select id="process_id"class="form-control js-example-basic-single" name="agency_id" >
                          		<option  value="0">Tất Cả</option>;
                               <?php foreach($processes as $process){
                                 echo "<option  value=".$process->id.">".$process->name."</option>";
                                }?>
                          </select>
                      </div>
                      <label for="inputEmail3" class="col-sm-2 control-label">Người Xử Lý</label>
                      <div class="col-sm-2">
                         <select id="provider_id"class="form-control js-example-basic-single" name="agency_id" >
                               <?php foreach($agencys as $agency){
                                 echo "<option  value=".$agency->getId().">".$agency->getUsername()."</option>";
                                }?>
                          </select>
                      </div>
                    </div>
                  </div><!-- /.box-body -->
    </form>
	<div>
		Ẩn Hiện: 
		<a class="toggle-vis" data-column="1">Tên</a>
		 - <a class="toggle-vis" data-column="2">Hồ Sơ</a>
		 - <a class="toggle-vis" data-column="3">Trạng Thái</a> 
		  - <a class="toggle-vis" data-column="4">Người Gửi</a> 
		 - <a class="toggle-vis" data-column="5">Thỏa Thuận</a> 
		  - <a class="toggle-vis" data-column="6">Đã Nhận</a>
		 - <a class="toggle-vis" data-column="7">Ngày Nhận</a> 
		 - <a class="toggle-vis" data-column="8">Ngày Trả</a> 
	</div>
	<table id="users-table" class="display nowrap" cellspacing="0" width="100%">
	  
	          <thead>
	        
	            <tr>
	            	<th>#</th>
	                <th>Tên</th>
	                <th>Hồ Sơ</th>
	                <th>Trạng Thái</th>
	               	<th>Thỏa Thuận</th>
	               	<th>Đã Nhận</th>
	               	<th>Ngày Nhận</th>
	               	<th>Ngày Trả</th>
	            </tr>
	        </thead>
	        <tfoot>
	            <tr>
 					<th>#</th>
	                <th>Tên</th>
	                <th>Hồ Sơ</th>
	                <th>Trạng Thái</th>
	               	<th>Thỏa Thuận</th>
	               	<th>Đã Nhận</th>
	               	<th>Ngày Nhận</th>
	               	<th>Ngày Trả</th>
	            </tr>
	        </tfoot>
	</table>
</section>