  <!-- Main content -->
<section class="content">
<!-- Button trigger modal -->
  <!-- Main row -->
  <div class="row">
    <!-- Left col -->
    <section class=" col-lg-12 connectedSortable">
         <div class="box box-warning">
                  <div class="box-header with-border">
                                  <h3 class="box-title">Thông Tin Hồ Sơ Mã Số <span class="label label-default"><?php echo $task->id;?></h3>
                                  <div class="box-tools pull-right">
                                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                                  </div><!-- /.box-tools -->
                                </div><!-- /.box-header -->
                <div class="box-body">
                  <div role="form" class="form-horizontal">
                    <!-- text input -->
                    <div class="row">
                         <section class="col-lg-6 connectedSortable">
                            <div class="form-group">
                              <label for="inputName" class="col-sm-3 control-label">Tên Khách Hàng</label>
                              <div class="col-sm-9">
                               <label><?php echo $task->custumer;?></label>
                              </div>
                             </div>
                            <div class="form-group">
                               <label for="inputName" class="col-sm-3 control-label">Sản Phẩm</label>
                                  <div class="col-sm-9">
                                   <label><?php echo $task->certificate;?></label>
                                  </div>
                            </div>
                            <div class="form-group">
                               <label for="inputName" class="col-sm-3 control-label">Trạng Thái</label>
                                  <div class="col-sm-9">
                                      <label><?php echo $task->process_name;?></label>
                                  </div>
                            </div>
                        </section>
                        <section class="col-lg-6 connectedSortable">
                            <div class="form-group">
                              <label for="inputName" class="col-sm-6 control-label">Người Tạo</label>
                              <div class="col-sm-6">
                                  <label><?php echo $task->user_name;?></label>
                              </div>
                             </div>
                            <div class="form-group">
                               <label for="inputName" class="col-sm-6 control-label">Người Chỉnh Sửa Cuối Cùng</label>
                                  <div class="col-sm-6">
                                        <label><?php echo $task->last_user_name;?></label>
                                  </div>
                            </div>
                            <div class="form-group">
                               <label for="inputName" class="col-sm-6 control-label">Ngày Chỉnh Sửa</label>
                                  <div class="col-sm-6">
                                        <label><?php echo $task->last_update;?></label>
                                  </div>
                            </div>
                          
                        </section>
                    </div>
                      <div class="row">
                              <section class="col-lg-6 ">
                                   <div class="form-group">
                                   <label for="inputName" class="col-sm-3 control-label">Người Giám Sát</label>
                                      <div class="col-sm-9">
                                       <label><?php echo $task->reporter_name;?></label>
                                      </div>
                                  </div>
                              </section>
                                <section class="col-lg-6 ">
                                   <div class="form-group">
                                   <label for="inputName" class="col-sm-6 control-label">Người Chịu Trách Nhiệm</label>
                                      <div class="col-sm-6">
                                       <label><?php echo $task->assign_name;?></label>
                                      
                                      </div>
                                  </div>
                              </section>
                            </div>
                    </div><!-- /.box-body -->
             
                   </div><!-- /.box -->
                   <!-- file attachment -->
                   <div class="box box-default">
                      <div class="box-header with-border">
                        <h3 class="box-title">File Đính Kèm <small class="label pull-right bg-red" id="list_file_num">3</small></h3>
                        <div class="box-tools pull-right">
                        <button class="btn" onclick="show_upload_form()">Thêm File</button>
                          <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                        </div><!-- /.box-tools -->
                      </div><!-- /.box-header -->
                      <div class="box-body tab_height_box" style="display:none">
                        <ul class="todo-list ui-sortable" id="file_list">
                     
                        
                      </ul>
                      </div><!-- /.box-body -->
                    </div><!-- /.box -->
                    <!-- end file attachment -->
                    <div class="row">
                          <section class="col-lg-6 connectedSortable">
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                  <h3 class="box-title">Thông Tin Tài Chính</h3>
                                  <div class="box-tools pull-right">
                                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                                  </div><!-- /.box-tools -->
                                </div><!-- /.box-header -->
                            
                             <div class="box-body">
                               <div class="row">
                               <div class=" col-lg-6 form-group">
                                
                                </div>
                                <div class="col-lg-6 form-group">
                                  <label for="inputName" class="col-sm-6 control-label">Thỏa Thuận</label>
                                  <div class="col-sm-6">
                                   <label><?php echo $task->cost_buy;?></label>
                                  </div>

                                </div>
                                 </div>
                                <div class="row">
                                   <div class=" col-lg-6 form-group ">
                                    <label for="inputName" class="col-sm-6 control-label">Ngày Nhận</label>
                            
                                     <label><?php echo $task->date_open_pr; ?></label>
                                  </div>
                                   <div class=" col-lg-6 form-group">
                                    <label for="inputName" class="col-sm-6 control-label">Ngày Hẹn</label>
                                    <div class="col-sm-6">
                                    <label><?php echo $task->date_end_pr; ?></label>
                                    </div>

                                  </div>
                                    
                                </div>
                                  <div class="row">
                                   <div class=" col-lg-6 form-group ">
                                    <label for="inputName" class="col-sm-6 control-label">Thanh Toán</label>
                                    <div class="col-sm-6">
                                      <label><?php echo $pay_provider; ?></label>
                                    </div>
                                  </div>
                                   <div class=" col-lg-6 form-group">
                                     <label for="inputName" class="col-sm-6 control-label">Dư Nợ</label>
                                    <div class="col-sm-6">
                                       <label><?php echo $provider_debt; ?></label>
                                    </div>
                                  </div>
                                    
                                </div>
                                <div class="row">
                                   <label for="inputName" class="col-sm-3 control-label">Ghi Chú</label>
                                      <div  style="height: 130px ;overflow: scroll" class="col-sm-9">
                                           <label><?php echo $task->provider_note; ?></label>
                                      </div>                                      
                                </div>
                              

                            </div>
                        </div>
                        
                          </section>
                           <section class="col-lg-6 connectedSortable">
                        <div class="nav-tabs-custom">
                                <ul class="nav nav-tabs">
                                  <li class="active"><a href="#activity_pr" data-toggle="tab">Thanh Toán</a></li>
                                  <li><a href="#timeline_pr" data-toggle="tab">Bình Luận</a></li>
                                </ul>
                                <div class="tab-content">
                                  <div class="active tab-pane tab_height_box" id="activity_pr">
                                       <ul class="todo-list">
                                          <?php foreach ($provider_historys as $custumer_history) {?>
                                              <li>
                                              <!-- drag handle -->
                                              <span class="handle">
                                                <i class="fa fa-ellipsis-v"></i>
                                                <i class="fa fa-ellipsis-v"></i>
                                              </span>
                                              <!-- checkbox -->
                                          
                                              <!-- todo text -->
                                              <span class="text"><?php echo date_format(date_create($custumer_history->date_pay),"d/m/Y");?></span>
                                              <span class="text"><?php echo number_format($custumer_history->money)?></span>
                                             
                                               <small class="label label-success"><i class="fa fa-clock-o"></i> <?php echo $custumer_history->name;?></small>
                                                <!-- Emphasis label -->
                                              <small class="label label-danger"><i class="fa fa-clock-o"></i> <?php echo $custumer_history->username;?></small>
                                              <!-- General tools such as edit or delete-->
                                               <div class="tools">
                                                <i class="fa fa-edit" onclick='pay_edit(<?php echo $custumer_history->id;?>,2,<?php echo '"'.number_format($custumer_history->money).'"'?>,<?php echo  '"'.date_format(date_create($custumer_history->date_pay),"d/m/Y").'"';?>,<?php echo  '"'.$custumer_history->money_option.'"';?>,<?php echo  '"'.$custumer_history->note.'"';?>)'></i>
                                                <i class="fa fa-trash-o" onclick="confirm_delete(<?php echo $custumer_history->id;?>)"></i>
                                              </div>
                                            </li>
                                            </li>
                                          <?php }?>
                                          </ul>
                                  </div><!-- /.tab-pane -->
                                   <div class="tab-pane" id="timeline_pr">
                                     <div class="box-body chat box tab_height_box" id="provider-chat-box"  >
                                      
                                      <!-- chat item -->
                                      <div class="item">
                                        <img src="dist/img/user3-128x128.jpg" alt="user image" class="offline">
                                        <p class="message">
                                          <a href="#" class="name">
                                            <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 5:15</small>
                                            Alexander Pierce
                                          </a>
                                          I would like to meet you to discuss the latest news about
                                          the arrival of the new theme. They say it is going to be one the
                                          best themes on the market
                                        </p>
                                      </div><!-- /.item -->
                                    
                                    </div><!-- /.chat -->
                                    <div class="box-footer">
                                      <div class="input-group">
                                        <input class="form-control" id="provider-comment"placeholder="Type message...">
                                        <div class="input-group-btn">
                                          <button class="btn btn-success" 
                                          onclick="addcomment('provider-comment',2,<?php echo $task->id?>,'provider-chat-box',<?php echo "'".\Application\Config\Config::IMAGE_PATH."'";?>)">
                                          <i class="fa fa-plus"></i>
                                          </button>
                                        </div>
                                      </div>
                                    </div>
                                  </div><!-- /.tab-pane -->
                                </div><!-- /.tab-content -->
                              </div><!-- /.nav-tabs-custom -->
                          </section>
                    </div>
                  </div>
            
    </section><!-- /.Left col -->
    <!-- right col (We are only adding the ID to make the widgets sortable)-->
  </div><!-- /.row (main row) -->

</section><!-- /.content -->
<!-- Modal -->
<div class="modal fade" id="modal-confirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Cảnh Báo</h4>
      </div>
      <div class="modal-body">
            Dữ Liệu sẽ bị xóa
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
        <button type="button" class="btn btn-primary" id="delete-pay" >Xóa</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal upload  -->
<div class="modal fade" id="modal-upload" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Thêm File</h4>
      </div>
      <div class="modal-body">
            <form class="form-horizontal" id="upload_file_att" enctype="multipart/form-data">
                      <div class="form-group">
                        <label for="inputName" class="col-sm-4 control-label">Chọn File</label>
                        <div class="col-sm-6">
                          <input type="file" name="file_name" class="form-control ">
                          <input type="hidden" name="permission_option" value="3" class="form-control ">
                          <input type="hidden" class="form-control"  name="task_id" value="<?php echo $task->id;?>">
                        </div>
                      </div>
              </form>

      </div>
       <div class="progress progress-xxs" style="margin-bottom: 0px;">
                    <div class="progress-bar progress-bar-primary progress-bar-striped" role="progressbar" aria-valuenow="40" id="upload-file-process" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
                      <span class="sr-only">40% Complete (success)</span>
                    </div>
                  </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
        <button type="button" class="btn btn-primary btn ajax" id="add-file" onclick="add_file()" >Thêm</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

  function confirm_delete(id){
     $("#delete-pay").attr('onclick','delete_pay('+id+')');
      $("#modal-confirm").modal('show');
  }
  function pay_edit(id,type,money,date,money_option,note){
      init_pay_edit_form(id,type,money,date,money_option,note);
      $("#myModal").modal('show');

  }
  function show_upload_form(){
    $("#upload-file-process").css('width',"0%");
    $("#modal-upload").modal('show');
  }

  function progressHandlingFunction(e){
    if(e.lengthComputable){
        $("#upload-file-process").attr('value', e.loaded);
        $("#upload-file-process").attr('max', e.total);
        $("#upload-file-process").css('width',e.loaded*100/e.total+"%");
      }
  }
  function add_file(){
    var formData = new FormData($('#upload_file_att')[0]);
    console.log(formData);
    $.ajax({
        url: '/manager-tasks/addfile',  //Server script to process data
        type: 'POST',
        xhr: function() {  // Custom XMLHttpRequest
            var myXhr = $.ajaxSettings.xhr();
            if(myXhr.upload){ // Check if upload property exists
                myXhr.upload.addEventListener('progress',progressHandlingFunction, false); // For handling the progress of the upload
            }
            return myXhr;
        },
        //Ajax events
       // beforeSend: beforeSendHandler,
       success: function(){
         $("#modal-upload").modal('hide');
         getFileList(<?php echo $task->id;?>);
       },
     //   error: errorHandler,
        // Form data
        data: formData,
        //Options to tell jQuery not to process data or worry about content-type.
        cache: false,
        contentType: false,
        processData: false
    });
  }
  function change_permission(id){
    var permission = $("#permission_option").val();
      $.ajax({
            type:"POST",                          
            url:"/manager-tasks/editfile",
            data:{
                   id:id,
                   permission:permission
                   },
            success: function(data){
               $("#modal-change-permission").modal('hide');
              getFileList(<?php echo $task->id;?>);
            }
     });
  }
  function delete_file(id){
    $.ajax({
            type:"POST",                          
            url:"/manager-tasks/deletefile",
            data:{
                   id:id,
                   },
            success: function(data){
               $("#modal-confirm").modal('hide');
              getFileList(<?php echo $task->id;?>);
            }
     });
  }
  function download_file(id){
    window.location ='/manager-tasks/downloadfile?id='+id;
  }
  function show_modal_delete_file(id){
     $("#delete-pay").attr('onclick','delete_file('+id+')');
      $("#modal-confirm").modal('show');
  }
  function show_modal_change_permission(id,permission){
    $("#permission_option").val(permission);
    $("#modal-change-permission").modal('show');
     $("#btn-change-permission").attr("onclick","change_permission("+id+")");
  }
   getFileList(<?php echo $task->id;?>);

  function getFileList(task_id){
      $.ajax({
            type:"POST",                          
            url:"/manager-tasks/filelist",
            data:{task_id:task_id,
                   },
            success: function(data){
                   var filelist ="";
                    for(var i = 0 ; i < data.length ;i++){
                     filelist+="<li>"
                      filelist   +='<span class="text">'+changedateSQLtoVN(data[i].date_create)+'</span>';
                     filelist   +='<span class="text">'+data[i].file_name+'</span>';
                    
                     filelist+=  '<div class="tools"> ';
                     filelist+=  '<i class="fa fa-download" onclick="download_file('+data[i].id+')"></i>';
                      if(data[i].user_create == <?php echo $this->identity()->id;?> ){
                      filelist+=       '<i class="fa fa-trash-o" onclick="show_modal_delete_file('+data[i].id+')"></i>';
                      }
                      filelist+= '</div>';
                     filelist+=   '</li>';
                    }
                    $('#file_list').html(filelist);
                    $('#list_file_num').html(data.length);
                    

            }
        });
  }
  getCommentList('custumer-chat-box',<?php echo $task->id;?>,1,<?php echo "'".\Application\Config\Config::IMAGE_PATH."'"?>);
 getCommentList('provider-chat-box',<?php echo $task->id;?>,2,<?php echo "'".\Application\Config\Config::IMAGE_PATH."'"?>);
  </script>
