  <!-- Main content -->
<section class="content">
  <!-- Main row -->
  <div class="row">
    <!-- Left col -->
    <section class=" col-lg-offset-3 col-lg-6 connectedSortable">
         <div class="box box-warning">
                <div class="box-header with-border">
                  <h3 class="box-title">Tạo Tài Khoản</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <form role="form">
                    <!-- text input -->
                    <div class="form-group">
                      <label>Tài Khoản</label>
                      <input type="text" class="form-control" placeholder="Enter ...">
                    </div>
                    <div class="form-group">
                      <label>Mật Khẩu</label>
                      <input type="password" class="form-control"  >
                    </div>
                     <div class="form-group">
                      <label>Mật Khẩu Xác Nhận</label>
                      <input type="password"  class="form-control">
                    </div>
                    <div class="form-group">
                      <label>Quyền</label>
                      <select class="form-control">
                      <?php 
                        foreach ($roles as $role) {
                        echo "<option value=".$role->id.">".$role->name."</option>";
                        }
                      ?>
                      </select>
                    </div >
                   <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                          <button type="submit" class="btn btn-danger">Tạo Tài Khoản</button>
                        </div>
                      </div>

                  </form>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
    </section><!-- /.Left col -->
    <!-- right col (We are only adding the ID to make the widgets sortable)-->
   
  </div><!-- /.row (main row) -->

</section><!-- /.content -->