  <!-- Main content -->
<section class="content">
  <!-- Main row -->
  <div class="row">
    <!-- Left col -->
    <section class=" col-lg-offset-3 col-lg-6 connectedSortable">
         <div class="box box-warning">
                <div class="box-header with-border">
                  <h3 class="box-title">Tạo Tài Khoản</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <form role="form" method="post" onsubmit="return validateFormRegister()">
                    <!-- text input -->
                    <div class="form-group <?php if($usererror == 1){echo 'has-error';}?>">
                      <label>Tài Khoản</label>
                      <input type="text" class="form-control" name="username">
                    </div>
                    <div class="form-group">
                      <label>Mật Khẩu</label>
                      <input type="password" class="form-control" name="password" >
                    </div>
                     <div class="form-group">
                      <label>Mật Khẩu Xác Nhận</label>
                      <input type="password"  class="form-control" name="password1">
                    </div>
                    <div class="form-group">
                      <label>Quyền</label>
                      <select name="role" class="form-control">
                      <?php
                        foreach ($roles as $role) {
                        echo "<option value=".$role->id.">".$role->name."</option>";
                        }
                      ?>
                      </select>
                    </div >
                   <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                          <button type="submit" class="btn btn-danger">Tạo Tài Khoản</button>
                        </div>
                      </div>

                  </form>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
    </section><!-- /.Left col -->
    <!-- right col (We are only adding the ID to make the widgets sortable)-->

  </div><!-- /.row (main row) -->

</section><!-- /.content -->
<script type="text/javascript" language="javascript" >
 function validateFormRegister(){
  if($( "input[name='username']" ).val().length == 0 ){
    $( "input[name='username']" ).parent().addClass("has-error");
    return false;
  }
  $( "input[name='username']" ).parent().removeClass("has-error");
  $( "input[name='username']" ).parent().addClass("has-success");

  if($( "input[name='password']" ).val().length == 0 ){
    $( "input[name='password']" ).parent().addClass("has-error");
    return false;
  }
  $( "input[name='password']" ).parent().removeClass("has-error");
  $( "input[name='password']" ).parent().addClass("has-success");

   if($( "input[name='password1']" ).val().length == 0 ){
    $( "input[name='password1']" ).parent().addClass("has-error");
    return false;
  }
  $( "input[name='password1']" ).parent().removeClass("has-error");
  $( "input[name='password1']" ).parent().addClass("has-success");

  if($( "input[name='password1']" ).val() != $( "input[name='password']" ).val()){
      $( "input[name='password1']" ).parent().addClass("has-error");
      return false;
  }
  $( "input[name='password1']" ).parent().removeClass("has-error");
  $( "input[name='password1']" ).parent().addClass("has-success");
  return true;
 }
</script>