<section class="content">
	<table id="users-table" class="display" cellspacing="0" width="100%">
	         <thead>
	            <tr>
	                <th>Tài Khoản</th>
	                <th>Quyền</th>
	                <th>Trạng Thái</th>

	            </tr>
	        </thead>
	        <tfoot>
	            <tr>
	                <th>Tài Khoản</th>
	                <th>Quyền</th>
	                <th>Trạng Thái</th>
	            </tr>
	        </tfoot>
	</table>
</section>
<script type="text/javascript" language="javascript" class="init">

var editor; // use a global for the submit and return data rendering in the examples

	/*$('#users-talbe').DataTable( {
		dom: 'lrtip',
		processing: true,
        serverSide: true,
        ajax: {
            url: "/manager-users/getlist",
            type: "POST"
        },
		columns: [
			{ data: "username" },
			{ data: "role" },
			{ data: "staus" }
		],
		order: [[ 3, "desc" ]],
		buttons: [
			{ extend: "create", editor: editor },
			{ extend: "edit",   editor: editor },
			{ extend: "remove", editor: editor }
		]
	} );*/
		var table = $('#users-table').DataTable( {
						"dom": '<"top"iflp<"clear">>rt<"bottom"iflp<"clear">>',
						processing: true,
				        serverSide: true,
				        ajax: {
				            url: "/manager-users/getlist",
				            type: "POST"
				        },
				        "language": {
				    		"url": "//cdn.datatables.net/plug-ins/1.10.10/i18n/Vietnamese.json"
				  		},
						columns: [

							{ data: "username" },
							{ data: "role" },
							{ data: "status" }

						],

				} );
	 $('#users-table').on('click', 'tr', function () {
        //var data = table.row( this ).id();
        //alert( 'You clicked on '+data+'\'s row' );
        var data = table.row( this ).id();
        window.open("/profile/user-info/"+data);
    } );

</script>