<section class="content">
	<div class="box box-default">
		  <div class="box-header with-border">
		    <h3 class="box-title">
		    	Thêm Khóa Học <b style="color:red"><?php echo $certificate->certificate_name;?></b>
		    </h3>
		    <div class="box-tools pull-right">
		     <!--  <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button> -->
		    </div><!-- /.box-tools -->
		  </div><!-- /.box-header -->
		  <div class="box-body" >
		  	 <form role="form" method="POST" onsubmit="return validateFormCourse()">
                  <div class="box-body">
                    <div class="row">
                     <div class="form-group col-sm-3">
                      <label for="exampleInputEmail1">Tháng</label>
                      <div>
                      <select id="exampleInputEmail1" class="form-control cus-select2" name="month">
                      <?php 
                      	$i = 1;
                      	for($i = 1; $i< 13; $i++){
                      		echo '<option value="'.$i.'"> '.$i.'</option>';
                      	}
                      ?>
                     
                      </select>
                       </div>
                    </div>
                    <div class="form-group col-sm-3">
	                      <label for="exampleInputEmail1">Năm</label>
	                      <div>
	                      <select id="exampleInputEmail1" class="form-control cus-select2" name="year">
	                      <?php 
	                      	$i = 1;
	                      	for($i = 2013; $i< 2030; $i++){
	                      		echo '<option value="'.$i.'"> '.$i.'</option>';
	                      	}
	                      ?>
	                     
	                      </select>
	                       </div>
                    </div>
                    	
                    </div>
                   <div class="box-body">
                    <div class="row">
                     <div class="form-group col-sm-3">
                     	 <label for="start_time">Thời Gian Bắt Đầu</label>
	                     <input type="text" class="form-control cus_time cant_empty" id="start_time" name="start">
                    </div>
                    <div class="form-group col-sm-3">
	                
	                     <label for="start_end">Thời Gian Kết Thúc</label>
	                     <input type="text" class="form-control cus_time cant_empty" id="start_end" name="end">

                    </div>
                    	
                    </div>
                    <div class="row">
                     <div class="form-group col-sm-3">
                     	 <label for="finish_time">Ngày Cấp</label>
	                     <input type="text" class="form-control cus_time cant_empty" id="finish_time" name="finish">
	                      <input type="hidden" class="form-control " value="<?php echo $certificate->id;?>" name="certificate_id">
                    </div>
                   
                    	
                    </div>
                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Tạo Khóa Học</button>
                  </div>
                </form>
		</div>
	</div>

</section><!-- /.content -->
<script type="text/javascript">
	 $(".cus-select2").select2();
	 $("#start_time").datepicker( "option", "dateFormat", "dd/mm/yy");
	 $("#start_time").datepicker();
	 $("#start_end").datepicker( "option", "dateFormat", "dd/mm/yy");
	 $("#start_end").datepicker();
	 $("#finish_time").datepicker( "option", "dateFormat", "dd/mm/yy");
	 $("#finish_time").datepicker();

	 function validateFormCourse(){
	 	var is_erro = true;
		$('.cant_empty').each(function(){
			$(this).parent().removeClass("has-error");
    		$(this).parent().addClass("has-success");
    		if($(this).val().length == 0 ){
    			$(this).parent().removeClass("has-success");
       			$( this).parent().addClass("has-error");
       			
      	 		is_erro = false ;
   		 	}
		});
	 	return is_erro;
	 }
</script>