<?php use Application\Config\Config; ?>
<!-- Main content -->
<section class="content">
  <!-- Main row -->
  <div class="row">
    <!-- Left col -->
    <section class=" col-lg-offset-3 col-lg-6 connectedSortable">
         <div class="box box-warning">
                <div class="box-header with-border">
                  <h3 class="box-title">Tạo Chứng Chỉ</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                 <!-- alert-danger -->
                 <?php if (!empty($certificate_error)) { ?>
                  <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                    <?php
                        if (!empty($certificate_error['certificate_name'])) echo $certificate_error['certificate_name'];
                        if (!empty($certificate_error['create_date'])) echo $certificate_error['create_date'];
                    ?>
                  </div><!-- /.alert-danger  -->
                 <?php } ?>
                  <form role="form" method="post" onsubmit="return validateFormRegister()">
                    <!-- text input -->
                    <div class="form-group <?php if (!empty($certificate_error['certificate_name'])) { echo 'has-error';} ?>">
                      <label>Tên Chứng Chỉ</label>
                      <input type="text" class="form-control" name="certificate_name" value="<?php if (!empty($certificate)) { echo $certificate->getUsername(); } ?>">
                    </div>
                   <div class="form-group ">
                      <label>Địa Chỉ</label>
                      <select class="form-control" name="location_option">
                          <option value="1">Quê Quán</option>
                          <option value="2">Nơi Sinh</option>
                          <option value="3">Hộ Khẩu Thường Chú</option>
                      </select>
                    </div>
                 
                    <div class="form-group <?php if (!empty($certificate_error['certificate_note'])) { echo 'has-error';} ?>">
                      <label>Ghi Chú Chứng Chỉ</label>
                      <input  type="textarea"  class="form-control"  placeholder="Enter ..." name="certificate_note" value="<?php if (!empty($certificate)) { echo $certificate->getUsername(); } ?>">
                    </div>
                   <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                          <button type="submit" class="btn btn-danger">Tạo Chứng Chỉ</button>
                        </div>
                      </div>

                  </form>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
    </section><!-- /.Left col -->
    <!-- right col (We are only adding the ID to make the widgets sortable)-->

  </div><!-- /.row (main row) -->

</section><!-- /.content -->
<script type="text/javascript" language="javascript" >
 function validateFormRegister(){
  if($( "input[name='certificate_name']" ).val().length == 0 ){
    $( "input[name='certificate_name']" ).parent().addClass("has-error");
    return false;
  }
  $( "input[name='certificate_name']" ).parent().removeClass("has-error");
  $( "input[name='certificate_name']" ).parent().addClass("has-success");
  return true;
 }
</script>