<?php use Application\Config\Config; ?>
<!-- Main content -->
<section class="content">
  <!-- Main row -->
  <div class="row">
    <!-- Left col -->
    <section class=" col-lg-offset-3 col-lg-6 connectedSortable">
         <div class="box box-warning">
                <div class="box-header with-border">
                  <h3 class="box-title">Tạo Hồ Sơ Chứng Chỉ</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                 <!-- alert-danger -->
                 <?php if (!empty($certificate_error)) { ?>
                  <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                    <?php
                        if (!empty($certificate_error['certificate_name'])) echo $certificate_error['certificate_name'];
                        if (!empty($certificate_error['create_date'])) echo $certificate_error['create_date'];
                    ?>
                  </div><!-- /.alert-danger  -->
                 <?php } ?>

                  <form role="form" method="post" onsubmit="return validateFormRegister()">
                    <div class="form-group">
                      <label> Loại Chứng Chỉ</label>
                      <select name="certificate_type" class="form-control">
                      <?php
                        foreach ($certificates as $certificate) {
                            echo "<option value=" . $certificate->id . ">" . $certificate->certificate_name . "</option>";
                        }
                      ?>
                      </select>
                    </div >

                    <div class="form-group <?php if (!empty($certificate_error['full_name'])) { echo 'has-error';} ?>">
                      <label>Tên Khách Hàng</label>
                      <input type="text" class="form-control" name="full_name" >
                    </div>
                    
                    <div class="form-group <?php if (!empty($certificate_error['day_of_birth'])) { echo 'has-error';} ?>">
                      <label>Ngày Tháng Năm Sinh</label>
                      <input type="text" class="form-control" name="day_of_birth" value="<?php ?>">
                    </div>
                    
                    <div class="form-group <?php if (!empty($certificate_error['place_of_birth'])) { echo 'has-error';} ?>">
                      <label>Nơi Sinh</label>
                      <input type="text" class="form-control" name="place_of_birth" >
                    </div>
                
                    <div class="form-group <?php if (!empty($certificate_error['identity_card'])) { echo 'has-error';} ?>">
                      <label>Số Chứng Minh Nhân Dân</label>
                      <input type="text" class="form-control" name="identity_card" value="<?php ?>">
                    </div>

                    <div class="form-group <?php if (!empty($certificate_error['start_time'])) { echo 'has-error';} ?>">
                      <label>Thời Gian Bắt Đầu</label>
                      <input type="text" class="form-control" name="start_time" value="<?php ?>">
                    </div>

                    <div class="form-group <?php if (!empty($certificate_error['end_time'])) { echo 'has-error';} ?>">
                      <label>Thời Gian Kết Thúc</label>
                      <input type="text" class="form-control" name="end_time" value="<?php ?>">
                    </div>

                    <div class="form-group <?php if (!empty($certificate_error['certificate_code'])) { echo 'has-error';} ?>">
                      <label>Mã Số Chứng Chỉ</label>
                      <input type="text" class="form-control" name="certificate_code" value="<?php ?>">
                    </div>
                    
                    <div class="form-group <?php if (!empty($certificate_error['note'])) { echo 'has-error';} ?>">
                      <label>Ghi Chú</label>
                      <input type="textarea" class="form-control" name="note" placeholder="Enter ..." value="<?php ?>">
                    </div>
                    
                   <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                          <button type="submit" class="btn btn-danger">Tạo Hồ Sơ Chứng Chỉ</button>
                        </div>
                   </div>
                  </form>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
    </section><!-- /.Left col -->
    <!-- right col (We are only adding the ID to make the widgets sortable)-->

  </div><!-- /.row (main row) -->

</section><!-- /.content -->
<script type="text/javascript" language="javascript" >
 function validateFormRegister(){
  if($( "input[name='certificate_name']" ).val().length == 0 ){
    $( "input[name='certificate_name']" ).parent().addClass("has-error");
    return false;
  }
  $( "input[name='certificate_name']" ).parent().removeClass("has-error");
  $( "input[name='certificate_name']" ).parent().addClass("has-success");

  if($( "input[name='create_date']" ).val().length == 0 ){
    $( "input[name='create_date']" ).parent().addClass("has-error");
    return false;
  }
  $( "input[name='create_date']" ).parent().removeClass("has-error");
  $( "input[name='create_date']" ).parent().addClass("has-success");
  
  return true;
 }
</script>