<?php use Application\Config\Config;
use Utility\Date\Date; ?>

<!-- Main content -->
<section class="content">
  <!-- Main row -->
  <div class="row">
    <!-- Left col -->
    <section class="col-lg-7 connectedSortable">
      <div class="box box-default">
                <div class="box-header with-border">
                  <h3 class="box-title">Thống Kê Hồ Sơ</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <div class="row">
                    <div class="col-md-8">
                      <div class="chart-responsive">
                        <canvas id="pieChart" height="150"></canvas>
                      </div><!-- ./chart-responsive -->
                    </div><!-- /.col -->
                    <div class="col-md-4">
                      <ul id ="pieLegend"class="chart-legend clearfix">
                        
                      </ul>
                    </div><!-- /.col -->
                  </div><!-- /.row -->
                </div><!-- /.box-body -->
                <div class="box-footer no-padding">
                  <ul class="nav nav-pills nav-stacked">
                    <li><a >Tổng Hóa Đơn Đại Lý<span id="total-agency" class="pull-right text-green"></span></a></li>
                    <li><a >Đại Lý Đã Thanh Toán<span id="pay-agency" class="pull-right text-aqua"></span></a></li>
                    <li><a >Số Nợ Của Đại Lý<span id="det-agency" class="pull-right text-red"></span></a></li>
                     <li><a ></a></li>
                     <li><a >Tổng Hóa Đơn Nhà Cung Cấp<span id="total-provider" class="pull-right text-green"></span></a></li>
                    <li><a >Đã Thanh Toán Cho Nhà Cung Cấp<span id="pay-provider" class="pull-right text-aqua"></span></a></li>
                    <li><a >Số Nợ Chưa Thành Toán<span id="det-provider" class="pull-right text-red"></span></a></li>
                    <li><a ></a></li>
                    <li><a >Số Nợ Trên Hệ Thống<span id="det-money" class="pull-right text-red"></span></a></li>
                  </ul>
                </div><!-- /.footer -->
              </div><!-- /.box -->
      <!-- Chat box -->
      <div class="box box-success">
        <div class="box-header">
          <i class="fa fa-comments-o"></i>
          <h3 class="box-title">Thông Báo</h3>
          <div class="box-tools pull-right" data-toggle="tooltip" title="Status">
            <div class="btn-group" data-toggle="btn-toggle" >
              <button type="button" class="btn btn-default btn-sm active"><i class="fa fa-square text-green"></i></button>
              <button type="button" class="btn btn-default btn-sm"><i class="fa fa-square text-red"></i></button>
            </div>
          </div>
        </div>
        <div class="box-body chat" id="list-notifications">
          <!-- chat item -->
          <div class="item">
            <img src="/AdminLTE-2.3.0/dist/img/user4-128x128.jpg" alt="user image" class="online">
            <p class="message">
              <a href="#" class="name">
                <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 2:15</small>
                Mike Doe
              </a>
              I would like to meet you to discuss the latest news about
              the arrival of the new theme. They say it is going to be one the
              best themes on the market
            </p>
            <div class="attachment">
              <h4>Attachments:</h4>
              <p class="filename">
                Theme-thumbnail-image.jpg
              </p>
              <div class="pull-right">
                <button class="btn btn-primary btn-sm btn-flat">Open</button>
              </div>
            </div><!-- /.attachment -->
          </div><!-- /.item -->
         
        </div><!-- /.chat -->
        <div class="box-footer">
        <?php if($this->identity()->role_id <=2){?>
          <div class="input-group">

            <input class="form-control" id="input-notification" placeholder="Type message...">
            <div class="input-group-btn">
              <button class="btn btn-success" onclick="addNotification()"><i class="fa fa-plus"></i></button>
            </div>
          </div>
          <?php }?>
        </div>
      </div><!-- /.box (chat box) -->
     

    </section><!-- /.Left col -->
    <!-- right col (We are only adding the ID to make the widgets sortable)-->
    <section class="col-lg-5 connectedSortable">
    	<!-- Construct the box with style you want. Here we are using box-danger -->
		<!-- Then add the class direct-chat and choose the direct-chat-* contexual class -->
		<!-- The contextual class should match the box, so we are using direct-chat-danger -->
		<div class="box box-danger direct-chat direct-chat-danger">
		  <div class="box-header with-border">
		    <h3 class="box-title"> Hoạt Động Mới</h3>
		    <div class="box-tools pull-right">
		      <a href="/log"><span class="badge bg-red">Xem Tất Cả</span></a>
		      
		  </div><!-- /.box-header -->
		  <div class="box-body">
		    <ul class="todo-list">
  <?php foreach ($logs as $log) {
      /* Decode to array */
      $task = json_decode($log->value, true);
   ?>
      <li>
      <!-- drag handle -->
      <!-- checkbox -->
      <!-- todo text -->
        <span class="text">
            <!-- user link -->
            <a class="foucus-value" href="/profile/user-info/<?php echo $log->user_id; ?>"><?php echo $log->join_user_name; ?></a>

            <!-- Action edit -->
            <?php if ($log->action_id == (string)Config::EDIT_ACTION) {
                echo " đã thay đổi " . "<span class='foucus-value'>".$task['key_name']."</span>"; ?>
                <?php if (! empty($task['custumer'])) echo "của khách hàng <span class='foucus-value'>" . $task['custumer']. "</span>, chứng chỉ "; else echo " của chứng chỉ: "; ?>

                <a class ="foucus-value" href="/manager-tasks/detail/<?php echo $log->task_id; ?>"> <?php echo $log->join_task_name; ?> </a>
                <!-- If field reporter_id, agency_id ... -->
                <?php echo " từ "; ?>
                <?php if ($task['key'] == Config::reporter_id
                        || $task['key'] == Config::provider_id
                        || $task['key'] == Config::agency_id
                        || $task['key'] == Config::assign_id) {?>
                    <!-- Org link -->
                    <a class ="old-value foucus-value"href="/profile/user-info/<?php echo $task['old_id']; ?>"> <?php echo $task['old_value']; ?> </a>
                    <?php echo " sang "; ?>
                    <!-- new link -->
                    <a class ="foucus-value" href="/profile/user-info/<?php echo $task['new_id']; ?>"> <?php echo $task['new_value']; ?> </a> <?php
                } else if ($task['key'] == Config::process_id) {
                    echo "<span class='old-value foucus-value'>".$task['old_value'] ."</span>". " sang " ."<span class='new-value foucus-value'>".$task['new_value']."</span>";
                }  else if ($task['key'] == Config::date_open_id
                        || $task['key'] == Config::date_end_id
                        || $task['key'] == Config::date_open_pr_id
                        || $task['key'] == Config::date_end_pr_id) {
                    echo "<span class='old-value foucus-value'>". Date::changeDateSQLtoVN($task['old_id']) ."</span>". " sang " ."<span class='new-value foucus-value'>". Date::changeDateSQLtoVN($task['new_id']) ."</span>";
                } else if ($task['key'] == Config::agency_note_id
                        || $task['key'] == Config::provider_note_id) { ?>
                    <a href="#" data-toggle="tooltip" title="<?php echo $task['old_id']?>"> <?php echo "<span class='old-value foucus-value'>". substr($task['old_id'], 0, 50) ."</span>" ?></a>
                    <?php echo " sang "; ?>
                    <a href="#" data-toggle="tooltip" title="<?php echo $task['new_id']?>"> <?php echo "<span class='new-value foucus-value'>". substr($task['new_id'], 0, 50) ."</span>"; ?></a>
                <?php } else {
                    echo "<span class='old-value foucus-value'>".$task['old_id'] ."</span>". " sang " ."<span class='new-value foucus-value'>".$task['new_id']."</span>";
                }
            } ?>

            <!-- Action new -->
            <?php if ($log->action_id == (string)Config::ADD_ACTION) {
                echo " đã thêm hồ sơ "?>
                <?php if (! empty($task['custumer'])) echo "của khách hàng <span class='foucus-value'>" . $task['custumer']. "</span>, chứng chỉ "; else echo " của chứng chỉ: "; ?>
                <a href="/manager-tasks/detail/<?php echo $log->task_id; ?>"> <?php echo $log->join_task_name; ?> </a>
                <?php
            }?>
             <?php if ($log->action_id == (string)Config::DELETE_PAY_ACTION) {
                echo " đã xóa <span class='foucus-value'> Thanh Toán</span> ";
                if ($task['type'] == 1) echo " (Bên Khách Hàng) ";
                else echo "(Bên Nhà Cung Cấp) ";
                echo "<span class='old-value foucus-value'>".number_format($task['money'])."</span>";
                echo "cho hồ sơ "?>
                <?php if (! empty($task['custumer']))
                    echo "của <span class='foucus-value'>" . $task['custumer']. "</span>, chứng chỉ ";
                else echo " của chứng chỉ: "; ?>
                <a href="/manager-tasks/detail/<?php echo $log->task_id; ?>"> <?php echo $log->join_task_name; ?> </a>
                <?php
            }?>
             <!-- Action pay -->
            <?php if ($log->action_id == (string)Config::COMMENT_ACTION) {
                echo " đã <span class='foucus-value'> Thêm bình luận</span> ";
                echo "<span class='new-value  foucus-value'>".substr($task['comment'],0,10)."...</span>";
                echo "cho hồ sơ "?>
                <?php if (! empty($task['custumer']))
                    echo "của <span class='foucus-value'>" . $task['custumer']. "</span>, chứng chỉ ";
                else echo " của chứng chỉ: "; ?>
                <a href="/manager-tasks/detail/<?php echo $log->task_id; ?>"> <?php echo $log->join_task_name; ?> </a>
                <?php
            }?>
             <?php if ($log->action_id == (string)Config::FILE_ACTION) {
                echo " đã <span class='foucus-value'> Thêm tài liệu</span> ";
                echo "<span class='new-value  foucus-value'>".$task['file_name']."</span>";
                echo "cho hồ sơ "?>
                <?php if (! empty($task['custumer']))
                    echo "của <span class='foucus-value'>" . $task['custumer']. "</span>, chứng chỉ ";
                else echo " của chứng chỉ: "; ?>
                <a href="/manager-tasks/detail/<?php echo $log->task_id; ?>"> <?php echo $log->join_task_name; ?> </a>
                <?php
            }?>
            <?php if ($log->action_id == (string)Config::DELETE_FILE_ACTION) {
                echo " đã <span class='foucus-value'> Xóa tài liệu</span> ";
                echo "<span class='old-value  foucus-value'>".$task['file_name']."</span>";
                echo "cho hồ sơ "?>
                <?php if (! empty($task['custumer']))
                    echo "của <span class='foucus-value'>" . $task['custumer']. "</span>, chứng chỉ ";
                else echo " của chứng chỉ: "; ?>
                <a href="/manager-tasks/detail/<?php echo $log->task_id; ?>"> <?php echo $log->join_task_name; ?> </a>
                <?php
            }?>
            <!-- Action pay -->
            <?php if ($log->action_id == (string)Config::PAY_ACTION) {
                echo " đã <span class='foucus-value'> Thanh Toán</span> ";
                if ($task['type'] == 1) echo " (Bên Khách Hàng) ";
                else echo "(Bên Nhà Cung Cấp) ";
                echo "<span class='foucus-value'>".number_format($task['money'])."</span>";
                echo "cho hồ sơ "?>
                <?php if (! empty($task['custumer']))
                    echo "của <span class='foucus-value'>" . $task['custumer']. "</span>, chứng chỉ ";
                else echo " của chứng chỉ: "; ?>
                <a href="/manager-tasks/detail/<?php echo $log->task_id; ?>"> <?php echo $log->join_task_name; ?> </a>
                <?php
            }?>
            <?php if ($log->action_id == (string)Config::EDIT_PAY_ACTION) {
                echo " đã <span class='foucus-value'> Chỉnh sửa Thanh Toán</span> ";
                if ($task['new_value']['type'] == 1) echo " (Bên Khách Hàng) ";
                else echo "(Bên Nhà Cung Cấp) ";
                if(trim($task['old_value']['money']) != trim($task['new_value']['money'])){
                  echo "<span class='old-value foucus-value'>".number_format($task['old_value']['money'])."</span>";
                  echo "<span class='new-value foucus-value'>".number_format($task['new_value']['money'])."</span>";
                }
                if(Date::changeDateSQLtoVN($task['old_value']['date_pay']) != Date::changeDateSQLtoVN($task['new_value']['date_pay'])){
                  echo "<span class='old-value foucus-value'>".Date::changeDateSQLtoVN($task['old_value']['date_pay'])."</span>";
                  echo "<span class='new-value foucus-value'>".Date::changeDateSQLtoVN($task['new_value']['date_pay'])."</span>";
                }
                if(trim($task['old_value']['money_option']) != trim($task['new_value']['money_option'])){
                  echo "<span class='old-value foucus-value'>".($task['old_value']['money_option'] == '1'? "Tiền Mặt":"Chuyển Khoản")."</span>";
                  echo "<span class='new-value foucus-value'>".($task['new_value']['money_option'] == '1'? "Tiền Mặt":"Chuyển Khoản")."</span>";
                }
                echo "cho hồ sơ "?>
                <?php if (! empty($task['new_value']['custumer']))
                    echo "của <span class=' foucus-value'>" . $task['new_value']['custumer']. "</span>, chứng chỉ ";
                else echo " của chứng chỉ: "; ?>
                <a href="/manager-tasks/detail/<?php echo $log->task_id; ?>"> <?php echo $log->join_task_name; ?> </a>
                <?php
            }?>
            
            <!-- date -->
            <i><?php echo " vào ngày " ."<i class='foucus-value'>".Date::changeDateSQLtoVN($log->date);?></i></i>
        </span>
        <!-- General tools such as edit or delete-->
      
      </li>
  <?php
      }
  ?>
  </ul>
		  </div><!-- /.box-body -->
		  <div class="box-footer">
		   
		  </div><!-- /.box-footer-->
		</div><!--/.direct-chat -->


    </section><!-- right col -->
  </div><!-- /.row (main row) -->

</section><!-- /.content -->
<script type="text/javascript" language="javascript" >
function addNotification(){
   var notification = $("#input-notification").val();
   if(notification == ''){
    return ;
   }
   $("#input-notification").val("")
   $.ajax({
            type:"POST",                          
            url:"/application/add-notification",
            data:{
                   notification:notification,
                   },
            success: function(data){
              loadNotification();
            }
  });
 
}
loadNotification();
  function loadNotification(){
      $('#list-notifications').append("<div class='overlay'><i class='fa fa-refresh fa-spin'></i></div>");
     $.ajax({
          type:"POST",                          
          url:"/application/list-notification",
          data:{
                 },
          success: function(data){
               var chat ="";
              for(var i = 0 ; i < data.length ;i++){
                    chat +='<div class="item">';
                    chat +='<img src="<?php echo Config::IMAGE_PATH ;?>'+data[i].avatar+'" alt="user image" class="offline">';
                    chat +='<p class="message">';
                    chat +='  <a href="#" class="name">';
                    chat += '<small class="text-muted pull-right"><i class="fa fa-clock-o">'+changedateSQLtoVN(data[i].date)+'</i></small>';
                    chat +=  data[i].username;
                    chat +=  '</a>';
                    chat +=  data[i].notification;
                    chat +='</p>';
                    <?php if($this->identity()->role_id <=2){?>
                    chat +='<div class="pull-right"><button class="btn btn-primary btn-sm btn-flat">Xoá</button></div>';
                    <?php }?>
                    chat +='</div>';
             }
              $('#list-notifications').html(chat);
          
          }
       });
   }
  getReportTask();
  var color =["#f56954","#00a65a","#f39c12","#00c0ef","#3c8dbc","#d2d6de","#111111"];
  var color_class=["text-red","text-green","text-yellow","text-aqua","text-light-blue","text-gray","text-text-black"];
  function getReportTask(){
       $.ajax({
          type:"POST",                          
          url:"/application/get-report-tasks",
          data:{
                 },
          success: function(data){
              var pieChartCanvas = $("#pieChart").get(0).getContext("2d");
              var pieChart = new Chart(pieChartCanvas);
               var pieOptions = {
                //Boolean - Whether we should show a stroke on each segment
                segmentShowStroke: true,
                //String - The colour of each segment stroke
                segmentStrokeColor: "#fff",
                //Number - The width of each segment stroke
                segmentStrokeWidth: 1,
                //Number - The percentage of the chart that we cut out of the middle
                percentageInnerCutout: 50, // This is 0 for Pie charts
                //Number - Amount of animation steps
                animationSteps: 100,
                //String - Animation easing effect
                animationEasing: "easeOutBounce",
                //Boolean - Whether we animate the rotation of the Doughnut
                animateRotate: true,
                //Boolean - Whether we animate scaling the Doughnut from the centre
                animateScale: false,
                //Boolean - whether to make the chart responsive to window resizing
                responsive: true,
                // Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container
                maintainAspectRatio: false,
                //String - A legend template
                legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<segments.length; i++){%><li><span style=\"background-color:<%=segments[i].fillColor%>\"></span><%if(segments[i].label){%><%=segments[i].label%><%}%></li><%}%></ul>",
                //String - A tooltip template
                tooltipTemplate: "<%=value %> <%=label%> "
              };
                var PieData = [];
                var total = 0;
             for(var i = 0 ; i < data.length ;i++){
                  var person = {
                         value: data[i].count,
                        color: color[i],
                        highlight: color[i],
                        label: data[i].name
                      };
                      total+= parseInt(data[i].count);
                      PieData.push(person);
             }
           
            //Create pie or douhnut chart
            // You can switch between pie and douhnut using the method below.
            pieChart.Doughnut(PieData, pieOptions);
            var legend="";
            for(var i = 0 ; i < PieData.length ;i++){
                  legend+= "<li><i class='fa fa-circle-o "+color_class[i]+"'></i> "+PieData[i].label+" ("+PieData[i].value+"/"+total+")"+"</li>";
             }
           $('#pieLegend').html(legend);
          }
       });
  }
 $.ajax({
            type:"POST",                          
            url:"/application/get-report-money",
            data:{
                   },
            success: function(data){
              $('#total-agency').html(accounting.formatNumber(data['agency']));
              $('#pay-agency').html(accounting.formatNumber(data['agency_pay']));
              $('#det-agency').html(accounting.formatNumber(data['agency'] - data['agency_pay']));

              $('#total-provider').html(accounting.formatNumber(data['provider']));
              $('#pay-provider').html(accounting.formatNumber(data['provider_pay']));
              $('#det-provider').html(accounting.formatNumber(data['provider'] - data['provider_pay']));

              $('#det-money').html(accounting.formatNumber((data['agency'] - data['agency_pay'])-(data['provider'] - data['provider_pay'])));
            }
  });
  
</script>