  <!-- Main content -->
<section class="content">
  <!-- Main row -->
  <div class="row">
    <!-- Left col -->
    <section class="col-lg-7 connectedSortable">
      <!-- Chat box -->
      <div class="box box-success">
        <div class="box-header">
          <i class="fa fa-comments-o"></i>
          <h3 class="box-title">Thông Báo</h3>
          <div class="box-tools pull-right" data-toggle="tooltip" title="Status">
            <div class="btn-group" data-toggle="btn-toggle" >
              <button type="button" class="btn btn-default btn-sm active"><i class="fa fa-square text-green"></i></button>
              <button type="button" class="btn btn-default btn-sm"><i class="fa fa-square text-red"></i></button>
            </div>
          </div>
        </div>
        <div class="box-body chat" id="chat-box">
          <!-- chat item -->
          <div class="item">
            <img src="/AdminLTE-2.3.0/dist/img/user4-128x128.jpg" alt="user image" class="online">
            <p class="message">
              <a href="#" class="name">
                <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 2:15</small>
                Mike Doe
              </a>
              I would like to meet you to discuss the latest news about
              the arrival of the new theme. They say it is going to be one the
              best themes on the market
            </p>
            <div class="attachment">
              <h4>Attachments:</h4>
              <p class="filename">
                Theme-thumbnail-image.jpg
              </p>
              <div class="pull-right">
                <button class="btn btn-primary btn-sm btn-flat">Open</button>
              </div>
            </div><!-- /.attachment -->
          </div><!-- /.item -->
          <!-- chat item -->
          <div class="item">
            <img src="/AdminLTE-2.3.0/dist/img/user3-128x128.jpg" alt="user image" class="offline">
            <p class="message">
              <a href="#" class="name">
                <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 5:15</small>
                Alexander Pierce
              </a>
              I would like to meet you to discuss the latest news about
              the arrival of the new theme. They say it is going to be one the
              best themes on the market
            </p>
          </div><!-- /.item -->
          <!-- chat item -->
          <div class="item">
            <img src="/AdminLTE-2.3.0/dist/img/user2-160x160.jpg" alt="user image" class="offline">
            <p class="message">
              <a href="#" class="name">
                <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 5:30</small>
                Susan Doe
              </a>
              I would like to meet you to discuss the latest news about
              the arrival of the new theme. They say it is going to be one the
              best themes on the market
            </p>
          </div><!-- /.item -->
        </div><!-- /.chat -->
        <div class="box-footer">
          <div class="input-group">
            <input class="form-control" placeholder="Type message...">
            <div class="input-group-btn">
              <button class="btn btn-success"><i class="fa fa-plus"></i></button>
            </div>
          </div>
        </div>
      </div><!-- /.box (chat box) -->

     
    </section><!-- /.Left col -->
    <!-- right col (We are only adding the ID to make the widgets sortable)-->
    <section class="col-lg-5 connectedSortable">
    	<!-- Construct the box with style you want. Here we are using box-danger -->
		<!-- Then add the class direct-chat and choose the direct-chat-* contexual class -->
		<!-- The contextual class should match the box, so we are using direct-chat-danger -->
		<div class="box box-danger direct-chat direct-chat-danger">
		  <div class="box-header with-border">
		    <h3 class="box-title"> Chat Room</h3>
		    <div class="box-tools pull-right">
		      <span data-toggle="tooltip" title="3 New Messages" class="badge bg-red">3</span>
		      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
		      <!-- In box-tools add this button if you intend to use the contacts pane -->
		      <button class="btn btn-box-tool" data-toggle="tooltip" title="Contacts" data-widget="chat-pane-toggle"><i class="fa fa-comments"></i></button>
		      <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
		    </div>
		  </div><!-- /.box-header -->
		  <div class="box-body">
		    <!-- Conversations are loaded here -->
		    <div class="direct-chat-messages">
		      <!-- Message. Default to the left -->
		      <div class="direct-chat-msg">
		        <div class="direct-chat-info clearfix">
		          <span class="direct-chat-name pull-left">Alexander Pierce</span>
		          <span class="direct-chat-timestamp pull-right">23 Jan 2:00 pm</span>
		        </div><!-- /.direct-chat-info -->
		        <img class="direct-chat-img" src="/AdminLTE-2.3.0/dist/img/user1-128x128.jpg" alt="message user image"><!-- /.direct-chat-img -->
		        <div class="direct-chat-text">
		          Is this template really for free? That's unbelievable!
		        </div><!-- /.direct-chat-text -->
		      </div><!-- /.direct-chat-msg -->

		      <!-- Message to the right -->
		      <div class="direct-chat-msg right">
		        <div class="direct-chat-info clearfix">
		          <span class="direct-chat-name pull-right">Sarah Bullock</span>
		          <span class="direct-chat-timestamp pull-left">23 Jan 2:05 pm</span>
		        </div><!-- /.direct-chat-info -->
		        <img class="direct-chat-img" src="/AdminLTE-2.3.0/dist/img/user3-128x128.jpg" alt="message user image"><!-- /.direct-chat-img -->
		        <div class="direct-chat-text">
		          You better believe it!
		        </div><!-- /.direct-chat-text -->
		      </div><!-- /.direct-chat-msg -->
		    </div><!--/.direct-chat-messages-->

		    <!-- Contacts are loaded here -->
		    <div class="direct-chat-contacts">
		      <ul class="contacts-list">
		        <li>
		          <a href="#">
		            <img class="contacts-list-img" src="../dist/img/user1-128x128.jpg" alt="Contact Avatar">
		            <div class="contacts-list-info">
		              <span class="contacts-list-name">
		                Count Dracula
		                <small class="contacts-list-date pull-right">2/28/2015</small>
		              </span>
		              <span class="contacts-list-msg">How have you been? I was...</span>
		            </div><!-- /.contacts-list-info -->
		          </a>
		        </li><!-- End Contact Item -->
		      </ul><!-- /.contatcts-list -->
		    </div><!-- /.direct-chat-pane -->
		  </div><!-- /.box-body -->
		  <div class="box-footer">
		    <div class="input-group">
		      <input type="text" name="message" placeholder="Type Message ..." class="form-control">
		      <span class="input-group-btn">
		        <button type="button" class="btn btn-danger btn-flat">Send</button>
		      </span>
		    </div>
		  </div><!-- /.box-footer-->
		</div><!--/.direct-chat -->
      

    </section><!-- right col -->
  </div><!-- /.row (main row) -->

</section><!-- /.content -->